### ISSUE TITLE
Add docs how to use the package

### ISSUE THREAD

**Issue by certik** [scikit-build/scikit-build#10]
Is the goal of this package to create robust `setup.py` for cmake projects? Is there some example how to use it?

Here is the `setup.py` that we use in csympy (cmake C++ project with optional thin Python wrappers): https://github.com/sympy/csympy/blob/c9d29e5ced2089934d769115e3002a5f0be089bc/setup.py

It works, but I would prefer to actually install the Python wrappers/package using `make install` from cmake (which is well tested in our project). That way we just make sure that `make install` works, and `setup.py` only calls it. Currently we need to test a separate installation mechanism that `setup.py` uses.

**Comment by isuruf** [comment]
SymEngine (earlier CSymPy) is now using information from distutils to get the install location (`distutils.comman.install.install_platlib`), passing it to CMake and calling `make install` to install.

https://github.com/symengine/symengine.py/blob/686bff8bbbb4945d0dc826b6ff7485bf164b46e2/setup.py

**Comment by thewtex** [comment]
@isuruf well done.  Thanks for sharing!

**Comment by certik** [comment]
@thewtex it's very exciting --- the whole `setup.py` has less than 200 lines and it essentially uses messy distutils or setuptools to figure out what needs to be done, a then calls cmake to get it done, including installation on all platforms (Linux, Mac, Windows).

@scopatz We have now separated the Python wrappers into https://github.com/symengine/symengine.py, they require the pure C++ library https://github.com/symengine/symengine to be already installed. I first thought I can just use distutils without cmake, since all we need now is just a simple cython based wrapper. But then you still need to link it properly on all platforms, and things quickly become messy again. So we decided to use cmake anyway, even though our package is now essentially a regular Python package, with no C or C++ files except the Cython generated wrapper. Another advantage is that I actually use cmake directly, without setup.py, and everything works, including installation. But somebody else might prefer setup.py, which is now just a thin layer on top of cmake.

**Comment by thewtex** [comment]
@certik It is awesome!! Yes, the symengine work should definitely be used as a starting point for this project, which will allows others to re-use the work. "Soon" in the coming months we will put some serious time into this project.

Task number 0 will likely be to create a PyPI package for CMake itself, so this package can specify it as a dependency and it will not require manual installation.

**Comment by msarahan** [comment]
FWIW, it is a conda package these days...

**Comment by thewtex** [comment]
I think we should avoid the requirement of having conda or cmake installed. We should also use a system where use a known version of CMake. Hopefully we can avoid having to discover it in the PATH.

**Comment by msarahan** [comment]
Of course!  I think a much better solution is one that depends ONLY on python standard distribution tools.  I was just pointing out that conda already does much of the distribution hard work - uses known versions of CMake, and takes care of putting it on PATH.  But that requires using conda (which currently essentially requires running miniconda/anaconda distribution), which not everyone wants to be tied to.

**Comment by blowekamp** [comment]
Last I checked Anaconda does not have CMake for windows.

**Comment by msarahan** [comment]
This is not in Anaconda proper, but you should be able to conda install it.  This is a very recent addition.  CMake 3.3.1 is available.

**Comment by msarahan** [comment]
I did this because I use it internally for building out our windows packages.  Making it a conda package meant that I have less setup nonsense to do on any given new build machine.

**Comment by thewtex** [comment]
@msarahan Cool 8-)

**Comment by jcfr** [comment]
To  follow up:

> PyPI package for CMake itself, so this package can specify it as a dependency and it will not require manual installation.

There are now wheels for cmake available on pypi:
* https://pypi.python.org/pypi/cmake
* https://github.com/scikit-build/cmake-python-distributions

and also for ninja:
* https://pypi.python.org/pypi/ninja
* https://github.com/scikit-build/ninja-python-distributions

**Comment by pzelasko** [comment]
Is there an end-to-end example available somewhere? I mean, with a `CMakeLists.txt`, `setup.py`, some hello world C/C++/Cython code and commands required to build and install it (e.g. in a virtualenv)? It would be tremendously helpful in adoption of this library - which seems very useful to me. Maybe you could at least point me to some project which already uses it?

**Comment by jcfr** [comment]
Hi @pzelasko , 

Here are few examples that will shortly be integrated into the documentation (using sphinx gallery or similar). See https://github.com/scikit-build/scikit-build-sample-projects/tree/master/projects

Ultimately these examples will also automatically be published as standalone project on https://github.com/python-packaging-tutorial

In the mean time, let me know if you have any questions.

Also, if you are attending SciPy, I would be happy to help and talk.
