### ISSUE TITLE
TODO: Update existing checkout of scikit-build

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#102]
Et voila. 

As discussed in https://github.com/scikit-build/scikit-build/issues/85#issuecomment-234397635, "Reorganized master" has been forced pushed:

* History is now coherent
* Each change introduce only one set of change with a descriptive commit message

Based on your current situation, consider following the instructions reported below:

Cc: @scikit-build/developers 

### Existing checkout: without topic

```
git fetch origin
git reset --hard origin/master
```

If you also have a reference to your fork on github, consider also updating it:

```
git push name_of_your_fork master --force
```

### Existing checkout:  with topic - rebase instructions

To rebase your topic named `name_of_your_topic`:

```
git checkout master && git branch -M master-original
git fetch origin
git checkout -b master origin/master
git checkout name_of_your_topic
git rebase --onto master master-original name_of_your_topic
```

### More details

There are no differences between the reorganized master (be4a55e) and the former one (169894b):

```
$ git diff master-original..master-reorganized
# No differences
```

```
$ git show master-original 
commit 169894b610d13ba6f3679ff37f7e0d7fbb071f4e
Merge: 068dbcb 8f6a585
Author: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
Date:   Thu Jul 21 17:36:00 2016 -0400

    Merge pull request #101 from scikit-build/94-update-appveyor-badge
    
    ci/appveyor: Update badges to references new account. Fixes #94

$ git show master-reorganized
commit be4a55e97cb2dbce4fb569df4708c343f7155ce6
Merge: dc2091b a85ca6b
Author: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
Date:   Thu Jul 21 21:37:51 2016 -0400

    Merge branch '94-update-appveyor-badge-rebased' into master-reorganized
    
    * 94-update-appveyor-badge-rebased:
      ci/appveyor: Update badges to reference new account. Fixes #94
```

**Comment by thewtex** [comment]
done on my side

**Comment by jcfr** [comment]
Great. Thanks for the note.
Cc: @opadron

**Comment by thewtex** [comment]
*Allow Merge Commits* has been disabled in the GitHub project settings to help prevent issues like this in the future.

**Comment by jcfr** [comment]
Looks like enabling `Allow Merge Commits` and this issue are orthogonal.

To allow force pushing on master, `Protect this branch` was temporally disabled and then re-enabled. Then, this issue was created to give instruction to the project contributors.

I created a new issue to discuss how commits could be merged and history organized. See #110
