### ISSUE TITLE
Generated wheels do not have a platform specfied

### ISSUE THREAD

**Issue by thewtex** [scikit-build/scikit-build#106]
This is evident in the wheel file name (``none-any`) and in the METADATA file *Platform* entry, which is currently `UNKNOWN`.

**Comment by jcfr** [comment]
`package_data` have been abused to integrate the binary artefacts into the "wheel", there are few possible hacks:
* inject the platform info after the fact
or 
* create an `Extension` class responsible to invoke CMake and collect the artefacts

**Comment by jcfr** [comment]
See https://github.com/SimpleITK/SimpleITK/blob/master/Wrapping/Python/Packaging/setup.py.in#L47-L56

**Comment by jcfr** [comment]
See https://github.com/espdev/ITKPythonInstaller/blob/e698360e89f12d417431798f2d3117aff870cb26/setup.py.in#L31-L36

**Comment by thewtex** [comment]
Cool :-)
