### ISSUE TITLE
Cython 3.0 - .pxd file not found

### ISSUE THREAD

**Issue by rc** [scikit-build/scikit-build#1099]
Hello,

I maintain a project that uses scikit-build + Cython and that I am now trying to update for Cython 3.

While with Cython version 0.29.34 the build process works well, with Cython 3.0.10 a [`.pxd`](https://github.com/sfepy/sfepy/blob/master/sfepy/discrete/common/extmods/types.pxd) file used in a [`.pyx`](https://github.com/sfepy/sfepy/blob/master/sfepy/discrete/common/extmods/assemble.pyx) file in the same directory is not found:
```
[18/66] Generating C source sfepy/discrete/common/extmods/assemble.c
FAILED: sfepy/discrete/common/extmods/assemble.c /home/user/projects/sfepy-git/_skbuild/linux-x86_64-3.10/cmake-build/sfepy/discrete/common/extmods/assemble.c 
cd /home/user/projects/sfepy-git/_skbuild/linux-x86_64-3.10/cmake-build/sfepy/discrete/common/extmods && /home/user/.local/bin/cython --include-dir /usr/include/python3.10 /home/user/projects/sfepy-git/sfepy/discrete/common/extmods/assemble.pyx --output-file /home/user/projects/sfepy-git/_skbuild/linux-x86_64-3.10/cmake-build/sfepy/discrete/common/extmods/assemble.c
/home/user/.local/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/user/projects/sfepy-git/sfepy/discrete/common/extmods/assemble.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
cimport cython

import numpy as np
cimport numpy as np

from types cimport int32, float64, complex128
^
------------------------------------------------------------

/home/user/projects/sfepy-git/sfepy/discrete/common/extmods/assemble.pyx:10:0: 'types.pxd' not found
```

Manually adding the directory (on the command line) using `--include-dir` to the command
```
/home/user/.local/bin/cython --include-dir /usr/include/python3.10 /home/user/projects/sfepy-git/sfepy/discrete/common/extmods/assemble.pyx --output-file /home/user/projects/sfepy-git/_skbuild/linux-x86_64-3.10/cmake-build/sfepy/discrete/common/extmods/assemble.c
```
fixes this problem, so it seems that the directory of the `assemble.pyx` file is not in Cython's search path anymore.

I have tried adding `include_directories(.)` to [`CMakeLists.txt` ](https://github.com/sfepy/sfepy/blob/master/sfepy/discrete/common/extmods/CMakeLists.txt) but that did not help.

Does anyone have any idea how to fix that? Thanks!

**Comment by henryiii** [comment]
As a quick fix, I think you could set the include directory flag via `CYTHON_FLAGS`. Guessing it's `${CMAKE_CURRENT_SOURCE_DIR}`?

**Comment by rc** [comment]
> `--include-dir /usr/include/python3.10` - that' snot where `types.pxd` is, though? Edit: Oh, you mean you modify this, not that it's the working command line.

No, this is the generated command that fails. When I add another `--include-dir /home/user/projects/sfepy-git/sfepy/discrete/common/extmods`, the command succeds.

**Comment by henryiii** [comment]
I don't see anything about this in the changelog. Ah, I think the problem is that it's now compiling in Python `3str` syntax, instead of Python 2. In Python 3, `from types import ...` will import the stdlib module "types", instead of your local module. You should instead write `from .types import ...`, which will be your local module.

**Comment by rc** [comment]
Great, thank you! That was it. 

After adding the `.` in relevant files, I got some `relative cimport from non-package directory is not allowed` errors, but using the full path fixed that as well. (Not sure why it was necessary only in some of the files, but well...) :)

**Comment by rc** [comment]
I have successfully built the project with Cython 3, so I am closing this, thank you again! 

PS: Do you happen to know how to fix the `FutureWarning: Cython directive 'language_level' not set ...` in the output above?

**Comment by henryiii** [comment]
Your cython files should all have appropriate directives at the top, something like this:

```python
# cython: language_level = 3
```

https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives

(Cython 2 or 3)

**Comment by henryiii** [comment]
You can see an example in the Cython tab here: https://scikit-build-core.readthedocs.io/en/latest/getting_started.html

**Comment by rc** [comment]
OK, all is working now!
