### ISSUE TITLE
Adopt a "linear history" ?

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#110]
See http://www.bitsnbites.eu/?p=221

**Comment by jcfr** [comment]
As discussed in https://github.com/scikit-build/scikit-build/issues/102#issuecomment-234970621 , `Allow Merge Commits` has been disabled. Since it doesn't always make sense to squash commit, I am re-enabling it.

**Comment by thewtex** [comment]
I think a linear history is too burdensome with active development -- it requires to many unnecessary rebases when working on parallel topics.

**Comment by thewtex** [comment]
That said, we should not be merging a master into a topic branch.

**Comment by jcfr** [comment]
>  linear history is too burdensome with active development -- it requires to many unnecessary rebases when working on parallel topics.

Makes sense

> we should not be merging master into a topic branch

Also make sense. On a case by case, if there is a long running topic, developer should consider rebasing.

**Comment by opadron** [comment]
I am a huge fan of linearized histories.  (I'm honestly not sure how we ended up with that merge mishap.)

Some of my thoughts:
 - We should adopt a process for adding contributions that ensures the history remains linear.
 - We should keep merge commits.
   - Topic branches provide a hierarchical overlay structure that is worth preserving.
   - PRs then work as a sort of higher-level "commit"
   - Very useful with `git-bisect`, for example.
 - However, merge commits should also be functionally superfluous
   - every topic branch should be fast-forward-able.
   - requires every "merge" to have a strict ordering.
     - merges need to be sequential and therefore coordinated.
     - :-1: for @thewtex
 - I argue:
   - Maintaining a clean, easy-to-follow, linear history is worth the extra work.
   - For projects at our current size, it's not that much "extra" work.
   - If we grow, we should be able to scale our process by introducing sub-topics.
     - For example, a `testing` subtopic where @msmolens and I could be working on our own, integrating #100, #98, and #46.  In this case, we only need to coordinate merges amongst ourselves, and can integrate to master when ready.

**Comment by jcfr** [comment]
>I'm honestly not sure how we ended up with that merge mishap

The issue was different. I re-organized and pushed force the topic because it was inadvertently and  pre-emptively integrated. Now we requires CI checks to be green, it should help. 

> ensures the history remains linear

The system currently in place with occasional rebase when relevant works well enough I  think.

**Comment by opadron** [comment]
@jcfr I think we are in agreement.  We've been *mostly* following a linear history process already, but we should formalize exactly what that means.  To me, it means all commits are strictly ordered.
Extrapolating from that, we see that maintaining such a history requires all merges to be fast-forwards.

Is this what we want? Or, are we content with relaxing that constraint and having a history that is *mostly* linear?

**Comment by thewtex** [comment]
There is a big advantage to a non-linear history -- working in parallel on branches.  We should utilize this feature. This is the main difference between Git and RCS.

A linear history is not required to use the features described in the article -- bisect, revert, and tracking down the origin of a change all work fine with a non-linear history.

Rebasing before merging would require a lot of unnecessary rebases that would need to be done locally instead of merging via the GitHub web UI.

**Comment by jcfr** [comment]
Thanks for the feedback.

Here are the conclusion:
* linear history is too burdensome with active development -- it requires to many unnecessary rebases when working on parallel topics.
* rebasing against master is optional and will be request on a case by case (e.g integration of ancient topic that would result in a lot of merge conflicts)

If relevant, do not hesitate to post additional comment or re-open this topic.
