### ISSUE TITLE
skbuild, msvc and setuptools 74.0.0 fails 

### ISSUE THREAD

**Issue by janoesth** [scikit-build/scikit-build#1114]
We are using skbuild, msvc and setuptools in a mixed c++ & python project.
With the recent version of setup tools 74.0.0, our build pipeline giving the following error:

> `\`\` File "C:\\Windows\\Temp\\pip-build-env-vhzi0u5i\\overlay\\Lib\\site-packages\\skbuild\\platform_specifics\\windows.py", line 281, in **init** vc_env = \_get_msvc_compiler_env(VS_YEAR_TO_VERSION\[year\], toolset) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\\Windows\\Temp\\pip-build-env-vhzi0u5i\\overlay\\Lib\\site-packages\\skbuild\\platform_specifics\\windows.py", line 217, in \_get_msvc_compiler_env monkey.patch_for_msvc_specialized_compiler() # type: ignore\[no-untyped-call\] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'setuptools.monkey' has no attribute 'patch_for_msvc_specialized_compiler' error: subprocess-exited-with-error`

**Comment by clarisma** [comment]
The same thing happened to our build pipeline, as well. 
Yesterday's release of setuptools (74.0.0) seems to be the culprit.

Workaround is to specify an earlier version as a build requirement in `pyproject.toml`, e.g.:

> [build-system]
> requires = ["setuptools==69.2.0", "wheel", "cibuildwheel", "scikit-build==0.17.6", "ninja"]
> build-backend = "setuptools.build_meta"

(However, this prevents us from releasing for Python 3.13 on Windows)

See also: https://github.com/pypa/setuptools/issues/4608

**Comment by henryiii** [comment]
I’ll try to fix this later today. scikit-build-core is unaffected, by they way.

**Comment by clarisma** [comment]
Confirmed, now works with latest versions. Thanks for the quick fix!

**Comment by janoesth** [comment]
Thanks a lot for the very swift response, works here as well!
