### ISSUE TITLE
RFC: Required GitHub status checks

### ISSUE THREAD

**Issue by thewtex** [scikit-build/scikit-build#113]
I have enabled required status check passes on other repos, and it is a useful process that improves policy:

  https://help.github.com/articles/enabling-required-status-checks/

**Comment by msmolens** [comment]
That seems like a good idea to me.

**Comment by jcfr** [comment]
:+1

**Comment by thewtex** [comment]
Cool. All status checks have been enabled exception code coverage / project until we get our code coverage up. We made need to adjust as experience dictates.
