### ISSUE TITLE
Rename organization and project to scikit-build

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#19]
Hi @msarahan , @blowekamp , @scopatz and @PyCMake/owners 

We were thinking of renaming the project and organization to `scikit-build`, that would be more descriptive of what we are trying to achieve: 

 _Easier build for scientific packages embedding C/C++/Fortran extensions._

Let us know what you think, 
@thewtex, @jcfr

**Comment by scopatz** [comment]
Fine by me.

**Comment by blowekamp** [comment]
Sound like a fine name to me. As long as it come with more effort for this project it'd be great!

**Comment by msarahan** [comment]
+1 I like the new name

**Comment by jcfr** [comment]
Thanks everyone for your feedback.  The repo and org have been renamed.

Issue #20 will be next.
