### ISSUE TITLE
Update project name, description and related files/folders

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#20]
- [x] setup.py
- [x] README.rst
- [x] Rename directories
- [x] Remove old package from PyPI. Is there a way in PyPI to _redirect_ to an other package ?
- [ ] <s>Generate and upload renamed package</s>

**Comment by thewtex** [comment]
CC @opadron

**Comment by opadron** [comment]
I remember seeing a discussion on the distutils list a few days ago about redirecting.  There were a lot of good reasons given as to why redirecting should be avoided.  I believe the consensus was that package maintainers should just switch to their new package, and push an update to the old one that spams the bejeezus out of its users with deprecation warnings. :)

**Comment by jcfr** [comment]
> good reasons given as to why redirecting should be avoided

For reference: https://mail.python.org/pipermail/distutils-sig/2016-April/028496.html

In that case, as soon as we have a version of scikit-build uploaded, I suggest we remove the pycmake one.

**Comment by jcfr** [comment]
Closing. Item `Generate and upload renamed package` will be tracked separately.
