### ISSUE TITLE
Rename PyCMake to skbuild

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#21]

**Comment by jcfr** [comment]
Renaming to `skbuild` is consistent with naming of `scikit-image / skimage`m `scikit-learn / sklearn`

**Comment by jcfr** [comment]
Cc: @thewtex

**Comment by thewtex** [comment]
@opadron Can this be closed?

**Comment by opadron** [comment]
Sorry I was late to the discussion.  This should be taken care of by #25.
