### ISSUE TITLE
Can't install with miniconda

### ISSUE THREAD

**Issue by mivade** [scikit-build/scikit-build#212]
On OS X at least, I get the following error when trying to install via `pip`:

```
Collecting scikit-build
  Using cached scikit_build-0.4.0-py2.py3-none-any.whl
Collecting setuptools==28.3.0 (from scikit-build)
  Using cached setuptools-28.3.0-py2.py3-none-any.whl
Requirement already satisfied: wheel==0.29.0 in /Users/depalati/miniconda3/envs/skb/lib/python3.5/site-packages (from scikit-build)
Installing collected packages: setuptools, scikit-build
  Found existing installation: setuptools 27.2.0
Cannot remove entries from nonexistent file /Users/depalati/miniconda3/envs/skb/lib/python3.5/site-packages/easy-install.pth
```

I get similar errors when trying to install in the root conda environment.

Is there a need for a hard requirement on setuptools 28.3.0?

**Comment by jcfr** [comment]
Hi @mivade 

Thanks for your report.

The error message reported is a know issue with conda, using the option `--ignore-installed` to pip is a possible workaround. See https://github.com/cdeepakroy/slicer_cli_web_plugin/commit/f1fb9b3c2fa835f20cfbf3e9834da1d901bc3ab5 for more details.

That said, setuptools==28.3.0 is not a hard requirement, it is the version we test against. Would it help to change this with `setuptools>=28.3.0` or a older version known to work ?

**Comment by mivade** [comment]
Using `--ignore-installed` does indeed work.

I get setting a version of setuptools used in testing, but given that setuptools is rather stable (as far as I know) and the wide variety of Python installations in the wild, I would think setting the required version to be a bit older would be more sensible, especially given that `--ignore-installed` could in principle be rather destructive.

Closing since the workaround is enough for now.

**Comment by jcfr** [comment]
> setuptools is rather stable ...  setting the required version to be a bit older would be more sensible,

Would `28.0.0` be a good trade-0ff ?

**Comment by mivade** [comment]
Considering the target audience is likely using anaconda/miniconda, I would think the most sensible thing is to use the version used there as the minimum version. A quick check indicates that `setuptools` is at version 28.8 there, so I think requiring `>=28.0.0` should work.
