### ISSUE TITLE
Transition readthedocs

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#22]
From http://pycmake.readthedocs.org to http://scikit-build.readthedocs.org

**Comment by jcfr** [comment]
New readthedocs has been setup: http://scikit-build.readthedocs.org/

@msarahan Would it be possible to take down http://pycmake.readthedocs.org/en/latest 

Merci

**Comment by msarahan** [comment]
Done!

**Comment by jcfr** [comment]
:cake:
