### ISSUE TITLE
Add `pytest-virtualenv` to conda-forge

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#228]
Adding this package to conda-forge would allow to remove the duplicated copy of `which` function and the disabling for  `test_distributions`.

```
Error: Packages missing in current linux-64 channels: 
  - pytest-shutil
  - pytest-virtualenv
```
Source: https://circleci.com/gh/conda-forge/scikit-build-feedstock/3

**Comment by isuruf** [comment]
`conda skeleton pypi pytest-shutil` will create a conda recipe automatically. You can then make necessary changes and send that as a PR to conda-forge/staged-recipes.

**Comment by jcfr** [comment]
Following up on this:
* `pytest-shutil` recipe submitted as https://github.com/conda-forge/staged-recipes/pull/6353

**Comment by jcfr** [comment]
Et voila, the recipe for pytest-virtualenv just got submitted. https://github.com/conda-forge/staged-recipes/pull/6367
