### ISSUE TITLE
Setup travis, appveyor and circleci

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#24]

**Comment by msarahan** [comment]
May I point you also to conda-forge?  https://conda-forge.github.io/ 

It is a community-originated project that continuum is moving towards.

This might simplify setup of those CI systems, and also provide packaging as a bonus.

**Comment by opadron** [comment]
Apparently, circleci needs admin access to the repo.

**Comment by jcfr** [comment]
You should be all set. Let me know if you are having issue.

@msarahan Thanks for the tip. Nice to see the CI results of all the feedstocks on https://conda-forge.github.io/feedstocks.html

**Comment by opadron** [comment]
Fixed in #32.
