### ISSUE TITLE
Set CMAKE_OSX_DEPLOYMENT_TARGET

### ISSUE THREAD

**Issue by thewtex** [scikit-build/scikit-build#247]
As described here:

  https://github.com/MacPython/wiki/wiki/Spinning-wheels

the OSX SDK version that the python we are building for uses can be determined by parsing:

```
python -c "import distutils.util; print(distutils.util.get_platform())"
```

scikit-build should use this on MacOSX to define `CMAKE_OSX_DEPLOYMENT_TARGET`:

https://cmake.org/cmake/help/v3.8/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html

So that the extension uses the same SDK as Python.

**Comment by jcfr** [comment]
Closing. Fixed in https://github.com/scikit-build/scikit-build/commit/d7a950a429b5dd9381d055383aaefb4eb47a254d
