### ISSUE TITLE
Specify architecture for Mac OSX wheels

### ISSUE THREAD

**Issue by thewtex** [scikit-build/scikit-build#248]
Ensure that `CMAKE_OSX_ARCHITECTURES`:

https://cmake.org/cmake/help/v3.8/variable/CMAKE_OSX_ARCHITECTURES.html

is set consistently according to the architecture in the `bdist_wheel` `--plat-name` option setting.

Generated binaries architecture, "universal" vs i386 vs x86_64, can be verified with the `file` command.

**Comment by blowekamp** [comment]
This is a good default behavior. If the OS X SDK is not available CMake will give a warning.

However, we need to ensure that the user can override. A older SDK is sometimes needed to ensure compatibility between Python distribution, as the pip known the SDKs are forwardly compatible.

The other related issues is that several distributions are still fat binaries and expect x86_64;i386 for CMAKE_OSX_ARCHITECTURES. This is much trickier for a default.

**Comment by jcfr** [comment]
Closing. Fixed in https://github.com/scikit-build/scikit-build/commit/d7a950a429b5dd9381d055383aaefb4eb47a254d

**Comment by jcfr** [comment]
xref #247
