### ISSUE TITLE
SciPy tutorial proposal

### ISSUE THREAD

**Issue by msarahan** [scikit-build/scikit-build#251]
Hi folks, I'm going to be putting in a proposal to teach a tutorial at SciPy this year on package building. I'm hoping to cover everything, including setup.py, wheels, binary compatibility, conda-build, and possibly scikit-build (though I'd need to refresh myself after all of your excellent work). Would anyone like to also join in on that proposal?

I would like to submit this proposal by Friday, Feb 24.

**Comment by thewtex** [comment]
@msarahan That's a great idea, and I think the SciPy community could greatly benefit from a package building tutorial. I would like to participate.

**Comment by jcfr** [comment]
Hi Mike,

Doing great. And thanks for reaching out, I am tottally psyched and would
gladly help out and participate

@thewtex: wanna join us ?

Jc

**Comment by jcfr** [comment]
Since our SciPy 2017 proposal got rejected, I am closing this issue.

**Comment by msarahan** [comment]
Better luck next year, I hope.
