### ISSUE TITLE
target_link_libraries_with_dynamic_lookup does not support [debug|optimized|general]

### ISSUE THREAD

**Issue by blowekamp** [scikit-build/scikit-build#255]
The following signature is not supported:
```
target_link_libraries(<target> [item1 [item2 [...]]]
                      [[debug|optimized|general] <item>] ...)
```

I am trying to get SimpleITK, compiled in debug, mode to link against the release python. By default on windows the debug library is suffixed with `_d.lib`. The need to be overridden by specifically specifying the release library in debug mode.

The current implementation interpret `debug` as a name of a library to link against.

**Comment by jcfr** [comment]
Thanks for the report.

Ideally, I think an imported library should probably be specified ... 
See https://cmake.org/cmake/help/v3.0/manual/cmake-buildsystem.7.html#imported-targets

If not, it look like [this line](https://github.com/scikit-build/scikit-build/blob/216d0648500cad61bfc6af287ecf461011e02fef/skbuild/resources/cmake/targetLinkLibrariesWithDynamicLookup.cmake#L538) could be updated using code like [this one](https://github.com/Kitware/CMake/blob/8cc9e07a2ca7018feb0dbc286f1db23a4294eeec/Modules/FindPythonLibs.cmake#L174-L183)

Pseudo code that could be added after [cmake/targetLinkLibrariesWithDynamicLookup.cmake#L538](https://github.com/scikit-build/scikit-build/blob/216d0648500cad61bfc6af287ecf461011e02fef/skbuild/resources/cmake/targetLinkLibrariesWithDynamicLookup.cmake#L538)

```
if(TARGET ${lib})
  _get_target_type(lib_type ${lib})
elseif(${lib} MATCHES "(debug|optimized|general)")
   # ignore
else()
  set(lib_type "SHARED")  # How do we handle case of static library ? 
endif()
```

**Comment by blowekamp** [comment]
Specifically this happens with linking against the python libraries on windows when debug and release libraries are installed. In such a case PYTHON_LIBRARIES can be defined as ` optimized;C:/Python35/libs/python35.lib;debug;C:/Python35/libs/python35_d.lib`

Looking towards a fix, it appears that `_get_target_type` is only designed for CMake targets and not for system libraries. The result of the function is therefore erroneous. I believe this is the case you question how to handle above. I don't know how that should be handled better. This function handles a large number of cases and options which I am not familiar with.

Just dropping the library type will not work as it should still be passed to target_link_libraries. I expect that the function will need to be rewritten so that each actual library is set in the for loop iteration.

**Comment by xoviat** [comment]
At configure item, `${PYTHON_LIBRARIES}` is set to this value:

```
optimized;optimized;optimized;optimized;optimized;optimized;optimized;optimized;optimized;optimized;optimized;optimized;optimized;optimized;optimized;/libs/python36.lib;optimized;optimized;optimized;optimized;optimized;optimized;optimized;debug;optimized;optimized;optimized;optimized;optimized;optimized;optimized;/libs/python36_d.lib;optimized;optimized;optimized;debug;optimized;optimized;optimized;/libs/python36_d.lib;optimized;debug;optimized;/libs/python36_d.lib;debug;/libs/python36_d.lib
```

At build time I receive this error:

```
LINK : fatal error LNK1181: cannot open input file 'optimized.lib'
```

I'm currently using this as a workaround:

```
# # Ensure that all of the libraries actually exist
# list(REMOVE_DUPLICATES PYTHON_LIBRARIES)
# foreach(library IN LISTS PYTHON_LIBRARIES)
#     if(NOT EXISTS "${library}")
#         list(REMOVE_ITEM PYTHON_LIBRARIES "${library}")
#     endif()
# endforeach()
```
