### ISSUE TITLE
Separate build folder for separate python versions.

### ISSUE THREAD

**Issue by isuruf** [scikit-build/scikit-build#283]
If I wanted to do something like
```
python3.4 setup.py build
python3.5 setup.py build
python3.4 setup.py install
python3.5 setup.py install
```
it would compile in each phase right? (wanted this functionality for building on Launchpad for multiple python versions)

Build directory can be deduced from distutils. That's what I currently do in symengine.py at https://github.com/symengine/symengine.py/blob/18b94bc2face4aca92ff60fd71d34f6aa2da9591/setup.py#L48 (Not using skbuild yet)

**Comment by jcfr** [comment]
Closing. Thanks to @xoviat , this is fixed in https://github.com/scikit-build/scikit-build/commit/410295203ce3dcd56abc02f83e3b067cccc76b27

**Comment by jcfr** [comment]
Duplicate #242
