### ISSUE TITLE
Extensions are not correctly installed

### ISSUE THREAD

**Issue by ghost** [scikit-build/scikit-build#293]
During [this build](https://travis-ci.org/symengine/symengine.py/jobs/343931342), the `install_data` step isn't run, and thus the extensions are not copied to the correct directory.

**Comment by xoviat** [comment]
The cause of this is that `find_packages` was not used. IMO scikit-build should at least warn when `install_data` will not be run.

**Comment by jcfr** [comment]
Is this still an issue ? 

I think this will be addressed by https://github.com/scikit-build/scikit-build/commit/53828061a2f5b484c74a2478d8bdff7e5511c431

**Comment by xoviat** [comment]
I haven't verified this, but it isn't a priority. In theory you must add one data file to guarantee that the install command is run.

**Comment by jcfr** [comment]
Closing this. Work-on on associated symengine.py issue has been resumed (see https://github.com/symengine/symengine.py/pull/219)
