### ISSUE TITLE
Where is "xoviat" ? 

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#309]
Does anyone know what happen to @xoviat, and why her/his account was replaced by the `ghost` one ? 

We were making some great progress on scikit-build, and would be great to move forward and collaborate further.

Thanks for your help, 
J-Christophe

**Comment by jcfr** [comment]
Last update I got was from March 5 2018, see https://github.com/scikit-build/scikit-build/pull/301#issuecomment-370205370

**Comment by msarahan** [comment]
I've seen comments about him deleting his account, but no one I've seen
knows why.

**Comment by jcfr** [comment]
Thanks for the update @msarahan , this is very strange. Do you know who else have been inquiring for her/him ? 

For archival purpose, here is a screenshot of a search of `github xoviat`:

![xoviat-2](https://user-images.githubusercontent.com/219043/37176896-c4ba8e90-22eb-11e8-8509-400d895d3348.png)

**Comment by msarahan** [comment]
I saw it at https://github.com/pypa/pip/issues/5033#issuecomment-371201590

**Comment by jcfr** [comment]
Thanks for the reference.

I think I found a point of contact [here](https://code.activestate.com/lists/python-distutils-sig/31555/), I will reach out and update this post with what I learn ...

**Comment by jcfr** [comment]
Update: xoviat is taking a well deserved break. 

The best we can do is acknowledge her/his contributions and move forward with our respective projects.

**Comment by msarahan** [comment]
Good for him/her.  I'm glad to hear that they are OK.  Rest well @xoviat

**Comment by Juanlu001** [comment]
@xoviat, wherever you are, thank you for all your awesome contributions. Rest well and hopefully see you soon.

**Comment by Juanlu001** [comment]
Sorry to revive this old thread, but after coming back to this topic, and just for the record and future Google searches:

http://numpy-discussion.10968.n7.nabble.com/xoviat-td45251.html

> His account was flagged by GitHub after scipy issue gh-8373. Flagging means your profile, and all your issue comments, PRs, etc. are all made private. It is quite bad if they don't come back; GitHub shouldn't break conversations like that by removing comments on a different repo made well prior to an incident. We'll be contacting GitHub about this.
