### ISSUE TITLE
Dies too soon with cmake missing

### ISSUE THREAD

**Issue by henryiii** [scikit-build/scikit-build#313]
skbuild fails to import if cmake is missing. This means that the following code will not work (untested, so it might not work as is, too):

```python
import subprocess

# Add CMake as a build requirement if cmake is not installed or is too low a version
setup_requires = []
try:
    cmake_version = subprocess.check_output(["cmake", "--version"])
    cmake_version = [int(x) for x in cmake_version.splitlines()[0].split()[-1].split('.')]
    if cmake_version < (3,4):
        setup_requires.append('cmake')
except OSError:
    setup_requires.append('cmake')
```

This forces the addition of `cmake` to the `pyproject.toml`, which could install an older version of cmake (3.10 instead of 3.11), and could affect the user (cmake from python might be installed in the path). If scikit build didn't fail until setup was run (and `setup_requires` was run), then the code at the beginning would be less invasive.

Note: testing code like this is easy with:

```bash
docker run -it ubuntu
apt update && apt install g++ python-pip python-dev git ninja-build
pip install pip==10.0b1
# get a scikit-build project and cd to it
python -m pip install .
```

Due to what I consider a bug in pip 10, you have to use `python -m pip` instead of `pip`.

**Comment by jcfr** [comment]
> skbuild fails to import if cmake is missing

It turns out `import skbuild` succeeds. The issue is that skbuild checks the version of CMake before calling `setuptools.setup` function.

**Comment by jcfr** [comment]
> This forces the addition of cmake to the pyproject.toml, which could install an older version of cmake (3.10 instead of 3.11)

Explicitly specifying the CMake version in `pyproject.toml` should ensure a newer version is installed:

```
[build-system]
requires = ["setuptools", "wheel", "cmake>X.Y.Z"]
```

**Comment by jcfr** [comment]
After #330 is integrated, the code above could be rewritten as:

```
from packaging.version import LegacyVersion
from skbuild.exceptions import SKBuildError
from skbuild.cmaker import get_cmake_version

# Add CMake as a build requirement if cmake is not installed or is too low a version
setup_requires = []
try:
    if LegacyVersion(get_cmake_version()) < LegacyVersion("3.4"):
        setup_requires.append('cmake')
except SKBuildError:
    setup_requires.append('cmake')
```

Note also that instead of appending `cmake`, you  could specify `cmake>=X.Y.Z`

that said, if installing the cmake wheel is not a problem, it is probably easier to do the following:

```
[build-system]
requires = ["setuptools", "wheel", "cmake>=X.Y.Z"]
```

**Comment by henryiii** [comment]
That looks good, the problem with doing a hard requirement on CMake is that running `pip install mypackage` could suddenly change the user's CMake for everything else to the pip one. This way it would only be added if the user's CMake is too old and has to be upgraded.

**Comment by jcfr** [comment]
Thanks for the feedback.

> could suddenly change the user's CMake for everything else to the pip one

I will add entries to a FAQ (or advanced section) to document the different approaches. By default, I think we should recommend creating a virtual env and using a `pyproject.toml` like the following:

```
[build-system]
requires = ["setuptools", "wheel", "scikit-build", "cmake", "ninja"]
```

That way, cmake and ninja will be available on in the virtual environment.

What do you think  ?

**Comment by henryiii** [comment]
I would agree with that (it will be automatic if the user uses pipenv, which is recommended by python.org - reducing to just `pipenv install mypackage` and `pipenv shell`). A mention in the advanced topics of the way to control based on the CMake version would be good, as well.

**Comment by jcfr** [comment]
> A mention in the advanced topics of the way to control based on the CMake version would be good, as well.

Done. See http://scikit-build.readthedocs.io/en/latest/usage.html#adding-cmake-as-building-requirement-only-if-not-installed-or-too-low-a-version
