### ISSUE TITLE
bdist_wheel does not include package data

### ISSUE THREAD

**Issue by reiver-dev** [scikit-build/scikit-build#315]
If package declares `include_package_data=True` and defines files in MANIFEST.in, they are not included into whl if bdist_wheel is called. Workaround:  `python setup.py build_py && python setup.py bdist_wheel`. Attached testing project.

[skbuild_test.zip](https://github.com/scikit-build/scikit-build/files/1916296/skbuild_test.zip)

**Comment by jcfr** [comment]
Hi Andrey,

Thanks for the report. Out travelling, I should be able to have a look in 2
weeks.

Thanks
Jc
