### ISSUE TITLE
Select specific version of CMake to use

### ISSUE THREAD

**Issue by henryborchers** [scikit-build/scikit-build#317]
Maybe this already exists and I can't find the information on how to do it. 

When building Python extensions with Scikit build on Jenkins CI node, I might have multiple versions of CMake installed. I would like to know if there is a way, perhaps with an environment variable, to override the version on CMake on the path to another version installed somewhere else? Appending the path before running each job is getting really annoying,

**Comment by jcfr** [comment]
> Appending the path before running each job is getting really annoying,

Do you mean that doing something like this is not very practical:

```
PATH=/path/to/cmake-X.Y.Z:$PATH  test.sh
```

and you would prefer:

```
SKBUILD_CMAKE_EXECUTABLE=/path/to/cmake test.sh
```

or 

```
python setup.py --cmake-executable /path/to/cmake
```

**Comment by henryborchers** [comment]
That would be AWESOME!!!

Either method is fine but I think this one is is a cleaner.
    python setup.py --cmake-executable /path/to/cmake"

When creating a Jenkinsfile script for the CI, it makes calling it's as easy as...
 
    ${tool` 'Python3.6.3_Win64'} setup.py --cmake-executable ${tool 'CMake3.11.1'}

And then any of my build nodes will be able to have the right versions of the tools to build it.

FYI. It's my opinion that modifying the path is not as practical for writing CI testing scripts. It's possible and works most of the time but it's not always clear what needs to be cleaned up manually and what automatically gets taken care off.  I find avoiding path manipulation in general is best for setting up CI pipelines.
