### ISSUE TITLE
Create a new release ?

### ISSUE THREAD

**Issue by Luthaf** [scikit-build/scikit-build#324]
Would it be possible for you to create a new release of scikit-build ?

The last one was one year ago, and the current master contains a few bug fixes that I would like to have available. Specifically, even updating to 0.6.1 is blocked on conda-forge (https://github.com/conda-forge/scikit-build-feedstock/pull/4) due to a bug that was fixed in the mean time.

Thank you very much !

**Comment by jcfr** [comment]
Hi Guillaume,

Currently travelling. This will happen at the end of the week (if not
earlier) and before SciPy conference.

Thanks for your patience,
Jc

**Comment by Luthaf** [comment]
Great new! And thank you for your work :smiley: !

**Comment by jcfr** [comment]
Thanks for your patience. 

New release is available for download. See https://pypi.org/project/scikit-build/0.7.1/

**Comment by anthrotype** [comment]
awesome, thank you @jcfr!
