### ISSUE TITLE
[OSX] skbuild.setup defaults cmake_args without checking kwargs for the arguments.

### ISSUE THREAD

**Issue by yonip** [scikit-build/scikit-build#342]
OS: OSX/Darwin (testing on travis).

`setup` checks the command line arguments for `-DCMAKE_OSX_DEPLOYMENT_TARGET` and for `-DCMAKE_OSX_ARCHITECTURES`, and if they don't exist, it defaults them [here](https://github.com/scikit-build/scikit-build/blob/d8e4db57e0a930db75bd204e47b64ba83a7300bb/skbuild/setuptools_wrap.py#L461-L477). The issue with this is that if the user passed either of those arguments to setup via a kwarg. i.e. `setup(..., cmake_args=[..., "-DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.7"])`, it gets overwritten with the default, even when nothing had been passed to the command line. 
This causes builds to break for no apparent reason (see the reasons for [this PR](https://github.com/skvark/opencv-python/pull/110)). A simple fix is moving the lines where the command line arguments are added to the arguments passed via kwarg from [here](https://github.com/scikit-build/scikit-build/blob/d8e4db57e0a930db75bd204e47b64ba83a7300bb/skbuild/setuptools_wrap.py#L503-L506) to right above the block mentioned above. 
Since `cmake_args` is not referenced between line 477 and line 503, nothing will get more args than it expected, and CLI will still override the args passed via kwarg, but default will only be set if neither the CLI or kwarg `cmake_arg` are set.
If this is approved I will [PR the fix](https://github.com/yonip/scikit-build/commit/2546c18c246857679e469b2a84576e1f802baa65) described above. 
(This is an issue first because the contribution guidelines specify filing bugs before trying to fix them).

**Comment by jcfr** [comment]
Thanks for reporting the issue :+1: 

I will review and provide feedback later today.

**Comment by yonip** [comment]
I have found another bug, in [ `Cmaker.has_cmake_cache_arg`](https://github.com/scikit-build/scikit-build/blob/master/skbuild/cmaker.py#L60-L70), which would cause the tests to fail: since it traverses the list of parameters in order, `has_cmake_cache_arg(['-DOVERRIDE:STRING=A', '-DOVERRIDE:STRING=B'], 'OVERRIDE', 'B')` returns `False`, while the way command line arguments are parsed, `OVERRIDE` should be set to `'B'`.
The simple solution here is replacing the [iteration line](https://github.com/scikit-build/scikit-build/blob/master/skbuild/cmaker.py#L64) with `for arg in reversed(cmake_args):`, which will check that the last occurrence of `arg_name` is set to `arg_value`. 
If you agree, I can put the fix and additional test in this PR. Should the new test go in `tests/test_cmaker.py` or in a separate file? Should I copy this to another issue and resolve it in a separate set of commits?

**Comment by jcfr** [comment]
Thanks for following up with this :+1:  Very much appreciated :clap: 

> I have found another bug, in `CMaker.has_cmake_cache_arg`,

Good catch

> if you agree, I can put the fix and additional test in this PR. 
> Should the new test go in tests/test_cmaker.py or in a separate file? Should I copy this to another issue and resolve it in a separate set of commits?

For this one, adding a new entry to the existing test is sensible.

https://github.com/scikit-build/scikit-build/blob/f35ea46dbd92e010a5740ff140fe3a230893fd48/tests/test_cmaker.py#L37-L48

It would be great to submit this change in a dedicated Pull Request referencing this issue.

Consider also updating [CHANGES.rs](https://github.com/scikit-build/scikit-build/blob/master/CHANGES.rst)
