### ISSUE TITLE
Synergy btw ITKPythonInstaller + skbuild

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#35]
Look into https://github.com/espdev/ITKPythonInstaller and how skbuild could help

Cc: @thewtex

**Comment by jcfr** [comment]
Closing. 

ITK wheels can now be generated using this project: https://github.com/InsightSoftwareConsortium/ITKPythonPackage

**Comment by jcfr** [comment]
@espdev   You may be interested by https://github.com/InsightSoftwareConsortium/ITKPythonPackage

**Comment by espdev** [comment]
@jcfr it's great! Thanks!
