### ISSUE TITLE
pybind11 integration

### ISSUE THREAD

**Issue by leezu** [scikit-build/scikit-build#369]
https://github.com/pybind/pybind11/ is a lightweight header-only library that exposes C++ types in Python and vice versa, mainly to create Python bindings of existing C++ code. They provide a [`pybind11_add_module` function](https://github.com/pybind/pybind11/blob/06d021b/tools/pybind11Tools.cmake#L111) and suggest the following `CMakeLists.txt` for projects using `pybind11`:

```
cmake_minimum_required(VERSION 2.8.12)
project(cmake_example)

add_subdirectory(pybind11)
pybind11_add_module(cmake_example src/main.cpp)
```

This does not work with scikit-build. What is the best-practice for building pybind11 based projects with scikit-build?

Example project: https://github.com/pybind/cmake_example

**Comment by FlorianFranzen** [comment]
I am able to scikit-build together with pybind11 just fine, so what exactly is your issue? Could you post some logs, etc?

**Comment by leezu** [comment]
I was wondering about how to configure scikit-build best for a pybind11 project. I don't have the logs anymore, but above code snippet didn't work.
It's great if it works for you. Can you share a link to your project or the configuration? Then this issue can be closed

**Comment by FlorianFranzen** [comment]
I normally install pybind11 with whatever package manager is available. Building and installing it from source with CMake should yield the same result.

Then my projects look something like this:

```cmake
cmake_minimum_required(VERSION 3.1.0 FATAL_ERROR)

project(myproject VERSION 1.2.3 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 14)

find_package(pybind11 REQUIRED)

pybind11_add_module(mymodule mymodule.cpp)
```

**Comment by jcfr** [comment]
@FlorianFranzen Thanks for the follow up :+1: 

Would be stellar if you could contribute a minimal example to https://github.com/scikit-build/scikit-build-sample-projects  :smile:

**Comment by FlorianFranzen** [comment]
There are already very similar examples in that repository. What exactly are you looking for in a new example?

**Comment by phcerdan** [comment]
I have added a pybind11 example project. Hope it helps.

The key is is to let pybind11 do the work, and use `__init__.py` files to define module dependencies, and import the library generated by pybind11. There is no use of `skbuild` CMake functions, or any extra option in the `setup.py`.
