### ISSUE TITLE
Integrate (itk|vtk)TargetLinkLibrariesWithDynamicLookup module in upstream CMake

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#37]
See: 
   https://gitlab.kitware.com/vtk/vtk/merge_requests/1511
   http://review.source.kitware.com/#/c/21091/
   http://review.source.kitware.com/#/c/21121/

We will have to discuss  how it could be best integrated.

Cc: @thewtex @demarle

**Comment by opadron** [comment]
I've had a look, and it seems like 90% of the what the change sets are doing is already implemented in #36/#38.  The remaining 10% is a try-compile that does a better job of determining when a linking can be weak.

In my (humble) opinion :), I think the best place for this functionality is directly in the `target_link_libraries` command as a new keyword ("WEAK", perhaps?).

Anyway, with _some_ official equivalent to `target_weak_link_libraries`, we could just update [these lines](https://github.com/opadron/scikit-build/blob/wip-2016-06-06/tests/samples/cmake-files/FindPythonExtensions.cmake#L323-L327) to take advantage of it.  No need to integrate anything beyond this one piece.

**Comment by jcfr** [comment]
For reference, CMake proposal available here [CMake: Proposal for adding Weak Linking support](https://docs.google.com/document/d/1e46rbbedffiQLHSRWwjuO9tbscOM9fXhWarL8eNhG5o/edit#)

**Comment by opadron** [comment]
Fixed in #47

**Comment by jcfr** [comment]
> We think upstreaming this module to CMake would be a worthwhile
> addition since it addresses a software integration need that is
> likely to be shared across multiple projects.

From @bradking:

It's worth considering, though some discussion of names, tests,
etc. is needed.  I often like to let these things mature in the
projects that need them first to reduce the risk of needing to
make breaking changes and keep compatibility implementations around.

As for naming, why is "_with_dynamic_lookup" chosen over "_weakly"
or something like that?  How widely use is the "weak linking" term?

The "target_link_libraries_" prefix may not be ideal.  It implies
that linking is always done, when in fact its intent is to not link
when possible.  Is there another name we can use for the
module/function that more accurately describes the intent/concept?
The name should communicate the intent to use dynamic lookup but
fall back to linking if necessary.

**Comment by jcfr** [comment]
Waiting the module "mature" in scikit-build, I am closing this issue.

**Comment by thewtex** [comment]
CC: @michkapopoff
