### ISSUE TITLE
Update conda-forge package for Python 3.5

### ISSUE THREAD

**Issue by jrmadsen** [scikit-build/scikit-build#372]
I am getting the following issue on Travis with conda-forge + scikit-build + Python 3.5 because the conda-forge package is out-of-date (this issue has been fixed):

> Traceback (most recent call last):
  File "/home/travis/build/jrmadsen/tomopy/setup.py", line 6, in <module>
    from skbuild import setup
  File "/home/travis/miniconda/lib/python3.5/site-packages/skbuild/__init__.py", line 9, in <module>
    from .setuptools_wrap import setup  # noqa: F401
  File "/home/travis/miniconda/lib/python3.5/site-packages/skbuild/setuptools_wrap.py", line 40, in <module>
    from .command import (build, build_py, clean,
  File "/home/travis/miniconda/lib/python3.5/site-packages/skbuild/command/bdist_wheel.py", line 6, in <module>
    from wheel import archive as _wheel_archive
ImportError: cannot import name 'archive'

Here is the package info:

> scikit-build-0.8.0         |   py35hfc679d8_0         110 KB  conda-forge

**Comment by jcfr** [comment]
Thanks for reporting the issue.

There only package for py27 and py36 on conda

![image](https://user-images.githubusercontent.com/219043/49673670-40170680-fa3d-11e8-89b4-64f7236e55df.png)


Look like we need to add more entry in the appveyor matrix here: https://github.com/conda-forge/scikit-build-feedstock/blob/master/.appveyor.yml

As detailed [here](https://github.com/conda-forge/scikit-build-feedstock#updating-scikit-build-feedstock), the build number in [recipe/meta.yaml](https://github.com/conda-forge/scikit-build-feedstock/blob/5b1faa128400b88d519c2c0339a2ce7c2c0cbb61/recipe/meta.yaml#L14-L15) would need to be increased to 1.

Would really appreciate you help :smile: 

Would it be possible to update the appveyor.yml file and submit a Pull Request for the project https://github.com/conda-forge/scikit-build-feedstock

**Comment by jrmadsen** [comment]
Sure I can do that np

**Comment by msarahan** [comment]
Conda-forge has dropped python 3.5 from its build matrix.  You can add this back, but it'll probably keep getting dropped by new PRs from the bot.

**Comment by jcfr** [comment]
Thanks for the feedback @msarahan  That make sense.

It was indeed removed with the last PR, see https://github.com/conda-forge/scikit-build-feedstock/commit/6cc44b2b4aa064e499f929b8fbb54ae473bef750

Since end of life for python 3.5 is set to Sept 2020, I suggest we keep it and also add Python 3.7 (https://github.com/scikit-build/scikit-build/issues/373)

See https://devguide.python.org/#status-of-python-branches

**Comment by jrmadsen** [comment]
I was going to go ahead and add Python 3.7

**Comment by jcfr** [comment]
That is awesome, thanks @jrmadsen

**Comment by jrmadsen** [comment]
@msarahan How do I modify the bot to not remove the 3.5 and 3.7 additions? the PR is ready. Should I just open it without running `conda smithy rerender`?

**Comment by msarahan** [comment]
You don't modify the bot.  You ignore its PRs, and you forgo its help with keeping things up to date. Conda forge made a deliberate choice to drop python 3.5 because of finite resources. It's not coming back. Conda forge supports the two most recent python versions. If this package can be made noarch, that's a better way forward.

**Comment by jrmadsen** [comment]
Ah... maybe a `legacy` branch (or `non-smithy`) would be the way forward. It could contain the configs that get deleted by the the bot and merged back into master on the occasions such as this -- where `scikit-build` is completely broken for a python version. Once conda-forge has been updated with these "legacy" Python versions, the PRs by the bot that deletes them again can be accepted.

**Comment by jcfr** [comment]
For reference, I just finalized the update of scikit-build-feedstock to build scikit-build 0.9.0, it also includes Python 3.5 (https://github.com/conda-forge/scikit-build-feedstock/commit/abb18f5ab491e2c9392cff587bd539f876a782ae)

**Comment by jcfr** [comment]
Closing. Package for Python 3.5 are available for scikit-build 0.9.0 and [release instructions](https://scikit-build.readthedocs.io/en/latest/make_a_release.html#conda-step-by-step) have been updated in https://github.com/scikit-build/scikit-build/commit/6ae80f9fd7d757130dc8846e433d57c069bf4c63

See:
* https://anaconda.org/conda-forge/scikit-build/files?version=0.9.0
* https://scikit-build.readthedocs.io/en/latest/make_a_release.html#conda-step-by-step
