### ISSUE TITLE
scikit-build extensions

### ISSUE THREAD

**Issue by jrmadsen** [scikit-build/scikit-build#374]
I want to run a couple idea by y'all before spending time developing:

1. Create a `configure` build command, e.g. `python setup.py configure`
    - This would run `cmake ...` directly, without building
    - This is easily added to setuptools with: `cmdclass=dict(configure=...)`
2. Better recognition of CMake args passed directly to compiler
    - If I specify `python setup.py build -- -DCMAKE_BUILD_TYPE=RelWithDebInfo`, don't have `--build-type` insert `-DCMAKE_BUILD_TYPE=Release`
3. Add support for a package I have written called [pyctest](https://github.com/jrmadsen/pyctest) [(docs)](https://pyctest.readthedocs.io/en/latest/about.html)
    - This would not be a requirement, just an optional extension (it requires building CMake from scratch since I create direct Python bindings to CMakeLib and CTestLib)
    - In general, it would allow scikit projects to directly submit to CDash, e.g.:
        - `python setup.py configure` inserted into CDash "Configure" section
        - `python setup.py build` inserted into CDash "Build" section
        - `python setup.py test` inserted into CDash "Test" section
        - Solve a (very) minor problem for PyCTest that causes a bunch of CMake/CTest files and folders (`CTestConfig.cmake`, `CTestCustom.cmake`, `Testing/`, etc.) being generated in the source directory for python project

**Comment by thewtex** [comment]
@jrmadsen thanks for discussing proposed changes and contributing! :+1: :clap: 

Deferring to @jcfr  -- note: he is away for the holiday, and may not respond until the new year.
