### ISSUE TITLE
How to use scikit build to link to archive files built with CMake?

### ISSUE THREAD

**Issue by manuel-castro** [scikit-build/scikit-build#388]
Hi,

I’m looking for a way to wrap a C++ project in Python to create a Python package, and it seems like scikit build would be ideal for my purposes, but I’m not sure how exactly to do it. I spent a long time reading about scikit build and setuptools yesterday but I’m still pretty lost as I’m new to creating python packages. I have a C++ project on my machine that builds with CMake and creates a few archive files. I’ve been using Cython to create a cpp file from a pyx file I wrote, and then in setup.py I’m creating an ext module that compiles the Cython generated cpp file and passes in the archive files as extra_link_args, so that I can call the C++ project from my python code. I would want to create my setup.py so that a user installing my package would run CMake and make on the C++ code, cythonize the pyx file, and then build the module with the linked archive files, just as I manually did on my machine. Is this something scikit build would be good for? I would greatly appreciate any help or advice anyone is willing to give.

**Comment by thewtex** [comment]
Hi @manuel-castro ,

One approach is to start with:

  https://github.com/scikit-build/scikit-build-sample-projects

These contain both C++ and Cython examples.

HTH,
Matt

**Comment by jcfr** [comment]
Thanks for reaching out @manuel-castro 

If your project is available on GitHub and if you open a PR to integrate scikit-build, we should be able to  provide some feedback.

**Comment by manuel-castro** [comment]
Thank you for the quick responses guys, I really appreciate it. Sorry I took a while to respond here. Once I figured out that scikit-build was essentially wrapping setuptools, it basically all "just worked" :D

All I had to do was specify cmake_source_dir and scikit-build ran cmake and then setuptools for me as I wanted. Thank you for scikit-build: a super useful tool!
