### ISSUE TITLE
Use PyPA recommended VS compilers

### ISSUE THREAD

**Issue by blowekamp** [scikit-build/scikit-build#40]
The PyPA has a guide line one the versions of compilers to use with difference versions of Python [1].

Specifically, I noticed that 2.7 was correctly compiled with VS9 2008, while py 3.5 was incorrectly compiled with VS10 2010.  From the document:

> Python 2.7 used Visual Studio 2008, Python 3.3 and 3.4 used Visual Studio 2010, and Python 3.5+ uses Visual Studio 2015.

[1] https://media.readthedocs.org/pdf/python-packaging-user-guide/develop/python-packaging-user-guide.pdf

**Comment by jcfr** [comment]
Good catch 

Looks like this test 
https://github.com/scikit-build/scikit-build/blob/f8038614c1b8d4c56a901bb0f05ba1962d30ecfc/tests/test_skbuild.py#L47-L50 along side the associated implementation should be tweaked.

See also https://github.com/scikit-build/scikit-build/issues/28#issue-147801050

**Comment by opadron** [comment]
@blowekamp it looks like the guidelines match with (at least) the intentions of the code (i.e.: mine).

So, two questions:

  - Are you saying that scikit-build incorrectly chose VS 2010 when running under Python 3.5?
  - Could you run the test suite (`nosetests -w tests`) and share the results?
    - If what you're observing really is an issue, *and* it wasn't caught by the tests, then that means both the implementation *and* the test need to be fixed.

**Comment by blowekamp** [comment]
I have not been following things closely, so I haven't tried to build or use this package yet.

My comment came from a look at a continuous integration output like this one:
https://ci.appveyor.com/project/opadron/scikit-build/build/0.0.1.91

It appears to be using VS2010 for python 3.5. Is that intended?

**Comment by jcfr** [comment]
Since this is a month old build .. that could explain the issue.

Otherwise, having an other look at https://github.com/scikit-build/scikit-build/blob/f8038614c1b8d4c56a901bb0f05ba1962d30ecfc/tests/test_skbuild.py#L47-L50 it looks right.

@opadron To avoid confusion, could you rename the boolean variables:
* `py_27_33` -> `py_27_32`
* `py_33_35` -> `py_33_34`

**Comment by opadron** [comment]
@jcfr Actually, I just figured it out: everything *is* working as intended, but I did overlook that we are overriding the default selection of generator in the appveyor test matrix.  It just so happens that I didn't change the version of visual studio to use for some of the tests.

I'll put in a quick PR to take care of that, and clarify those variables. :)

**Comment by jcfr** [comment]
Parfait. Merci :+1:
