### ISSUE TITLE
Undesirable behaviour with sdist and symlinks

### ISSUE THREAD

**Issue by anibali** [scikit-build/scikit-build#401]
When using `sdist` with setuptools, symlinks are replaced with the concrete files that they reference. I find this useful for keeping a version number consistent across multiple projects in the same repo.

In contrast, when using `sdist` with skbuild, the symlink is not followed, resulting in a (usually) useless symlink being added to the archive. This has proven to be a rather large annoyance in my current attempt at migrating a project over to scikit-build builds.

I have created a minimal example at https://github.com/anibali/issue-skbuild-sdist to exhibit both behaviours.

Steps to reproduce:

1. Clone https://github.com/anibali/issue-skbuild-sdist.
2. Run `SETUPTOOLS=1 python setup.py sdist` to use setuptools' `setup`.
3. Look at the contents of the produced tarball. The VERSION file will be a concrete file.
4. Run `python setup.py sdist` to use skbuild's `setup`.
5. Look at the contents of the produced tarball. The VERSION file will be a useless symlink.

Would using setuptools' sdist in scikit-build's sdist command be a possibility?: https://github.com/scikit-build/scikit-build/blob/master/skbuild/command/sdist.py#L6

**Comment by jcfr** [comment]
Thanks for the details report and the associated test case.

I was able to reproduce the problem.

> Would using setuptools' sdist in scikit-build's sdist command be a possibility?

Definitively, setuptools being a requirement, that makes sense.

I confirmed that this was working. Could you create a PR ? It may be sensible to  also add a small regression  test similar to  the existing [ones](https://github.com/scikit-build/scikit-build/tree/master/tests) (we have prefix `test_issueXXX`)

```diff
diff --git a/skbuild/command/sdist.py b/skbuild/command/sdist.py
index aa3230a..a55eea7 100644
--- a/skbuild/command/sdist.py
+++ b/skbuild/command/sdist.py
@@ -3,7 +3,7 @@
 import os
 
 from distutils import log as distutils_log
-from distutils.command.sdist import sdist as _sdist
+from setuptools.command.sdist import sdist as _sdist
 
 from . import set_build_base_mixin
 from ..utils import distribution_hide_listing, new_style

```

**Comment by anibali** [comment]
Sure, I'll work on putting together a PR soon.

**Comment by anibali** [comment]
The fix is more complicated than it initially seems. Switching to `setuptools.command.sdist` appears to exclude important files like CMakeLists.txt and C++ source files being excluded from the produced source archive. I'm actually not entirely sure by what mechanism these files were being included in the first place.

**Comment by anibali** [comment]
OK, so it looks like scikit-build generates a `MANIFEST` file automatically. From my understanding, `distutils` uses the `MANIFEST` file, but `setuptools` uses `MANIFEST.in` only and ignores `MANIFEST`.

**Comment by jcfr** [comment]
> it looks like scikit-build generates a MANIFEST file automatically

Indeed, this happen in https://github.com/scikit-build/scikit-build/blob/master/skbuild/command/generate_source_manifest.py

Related PRs: #310

**Comment by jcfr** [comment]
Closing. Corresponding changes integrated in https://github.com/scikit-build/scikit-build/pull/408
