### ISSUE TITLE
Document that setting MACOSX_DEPLOYMENT_TARGET env. variable is not supported

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#406]
See https://github.com/scikit-build/scikit-build/issues/362#issuecomment-470150020

**Comment by certik** [comment]
Here is a workaround how to make `setup.py` recognize this env variable: https://gitlab.com/lfortran/lfortran/merge_requests/229.

**Comment by jcfr** [comment]
Closing as there is no need to document it is not supported. Corresponding has been implemented in https://github.com/scikit-build/scikit-build/pull/441
