### ISSUE TITLE
Support for distributing generic wheel distributing convenience executable

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#420]
Work on https://github.com/scikit-build/scikit-build/pull/418 revealed there was no available CMake wheel for pypy.

### Current status

There is currently one CMake wheel per platform and per python version. For example:
```
cmake-3.13.3-cp27-cp27m-manylinux1_i686.whl 
[...]
cmake-3.13.3-cp27-cp27mu-manylinux1_x86_64.whl 
[...]
cmake-3.13.3-cp34-cp34m-macosx_10_6_x86_64.whl
[...]
cmake-3.13.3-cp36-cp36m-win_amd64.whl
[...]
```

Since there are no wheel with a `python tag` including `pypy` or `pypy3`, trying to run `pip install cmake` from a pypy interpreter [fails](https://github.com/scikit-build/scikit-build/pull/418#issuecomment-495091958).

### Toward more generic wheel

Since the CMake wheels (as well as ninja wheels) do not depend on Python C-API, @njsmith  suggested in https://github.com/pypa/manylinux/pull/273#issuecomment-468875632 that we should instead distribute less wheels by using the following convention:

```
cmake-X.Y.Z-py2.py3-none-manylinux2010_x86_64.whl
cmake-X.Y.Z-py2.py3-none-macosx_10_6_x86_64.whl
cmake-X.Y.Z-py2.py3-none-win_amd64.whl
```

This is a great idea and would reduce the number of wheels we have to build. That said, we would have to setup testing for all python version.

Reference:
* https://www.python.org/dev/peps/pep-0427/#file-name-convention
* wheel filename is `{distribution}-{version}(-{build tag})?-{python tag}-{abi tag}-{platform tag}.whl`

**Comment by mattip** [comment]
aside: it seems you could require `setuptools` and remove the check at the top of `setup.py`

**Comment by jcfr** [comment]
> aside: it seems you could require `setuptools` and remove the check at the top of `setup.py`

For reference, reply to this comment has been here: https://github.com/scikit-build/cmake-python-distributions/pull/70#issuecomment-495469864

**Comment by jcfr** [comment]
see https://github.com/anthrotype/wheeltools/issues/2

**Comment by jcfr** [comment]
See #359

**Comment by mattip** [comment]
Has this been solved now there are generic [cmake builds](https://pypi.org/project/cmake/#files) on PyPI?

**Comment by jcfr** [comment]
We can indeed close this issue.

Now that the wheeltools project has been transferred to the scikit-build organization (thanks to @anthrotype , see [here](https://github.com/scikit-build/wheeltools/pull/1#issuecomment-496443774) for more details about this), next step will  be to remove the `convert_to_generic_platform_wheel.py` script specific to [cmake-python-distribution](https://github.com/scikit-build/cmake-python-distributions/blob/aa9a0fd10838be4de6112a953924a183fec44c2a/scripts/convert_to_generic_platform_wheel.py) and [ninja-python-distributions](https://github.com/scikit-build/ninja-python-distributions/blob/4ff7559a2720da415db6df5e1523d67b111147f0/scripts/convert_to_generic_platform_wheel.py) and improve the wheeltools project accordingly.  See  scikit-build/wheeltools#2
