### ISSUE TITLE
cmaker.py: deprecated use of imp, unclosed file

### ISSUE THREAD

**Issue by Nic30** [scikit-build/scikit-build#429]
Hello,
I tried to run scikit-build with python3-dbg for Cython based C extension, there multiple problems.
(Extension is complicated so I am not reffering it, and the problem is not related to user code.)

Two of them, described below, should be easy to solve. 

* [x] imp module is deprecated in favour of importlib
```
/usr/lib/python3/dist-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
```

* [x] ResourceWarning: unclosed file 
```
/usr/local/lib/python3.7/dist-packages/skbuild/cmaker.py:425: ResourceWarning: unclosed file <_io.TextIOWrapper name='_skbuild/linux-x86_64-3.7/cmake-build/cmake_install.cmake' mode='r' encoding='utf-8'>
  for line in io.open(os.path.join(root, filename), encoding="utf-8"):
```
https://github.com/scikit-build/scikit-build/blob/master/skbuild/cmaker.py#L425

**Comment by jcfr** [comment]
Thanks for the report.

**Comment by jcfr** [comment]
The other issue related to the deprecated use of `imp` is associated with the setuptools package. See https://github.com/pypa/setuptools/blob/master/setuptools/depends.py

and it has already been reported as https://github.com/pypa/setuptools/issues/479

**Comment by Nic30** [comment]
Thank you for super fast fix.
