### ISSUE TITLE
Support for meson-build

### ISSUE THREAD

**Issue by Nic30** [scikit-build/scikit-build#432]
Hello,

I spend several years playing with buildsystems for embedded devices and I know autools/cmake/meson-build/SCons and others well.

The support for the python extensions in meson is not ideal, however this is because it is very easy to implement.
Meson is much more clean, readable and reliable than cmake. Has all it's functionality + better integration with other tools + can use cmake files as well.
Meson it self is very simple anyone can learn it in single day. On the other hand for cmake there is plenty of deprecated advices on the internet and the fact that the undefined variables can be used leads to annoying problems.

Another benefit is that meson is actually a python package.
I do have an experimental setup where I am using it.

Do you think that meson compatibility can be added to scikit-build somewhere in near future?

**Comment by jcfr** [comment]
Lacking experience with meson, I will not be able to provide a complete answer.

Considering that scikit-build was initially designed to leverage for build binary python wheels, and that cmake provides an exhaustive list of modules to find third-party libraries <sup>[1](https://cmake.org/cmake/help/latest/manual/cmake-modules.7.html#find-modules)</sup> along with the support for usage requirements <sup>[2](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#build-specification-and-usage-requirements), [3](https://www.lapthorn.net/blog/2018/05/08/Modern-CMake.html)</sup>, I would prefer we keep the project focused on cmake.


> I do have an experimental setup where I am using it.

That is great, would you have a link to share ?

**Comment by jcfr** [comment]
Also worth noting that official cmake tutorial are being integrated into the documentation, see https://github.com/Kitware/CMake/blob/master/Help/guide/tutorial/index.rst

**Comment by Nic30** [comment]
Short: Ok, close this issue.

Long (explanation why meson > cmake and it took minimal effort to create support for it):

> cmake provides an exhaustive list of modules 

meson uses also cmake to find libraries

* meson can do/use all the things from cmake

I was asking for the meson because:
* simple, reliable, readable, "normal programming language"
* easy to generate files and manage dependencies
* easy to generate files for other buildsystems/package managers
* support for any platform/compiler
* better config management

**Comment by Nic30** [comment]
> That is great, would you have a link to share ?

I can but the rest of library is quite complicated, and the only think I have done is I am calling meson from `build_ext`, `install_lib`, `bdist` classes with just paths/configs set. (Meson is just a python program.)

**Comment by jcfr** [comment]
> meson uses also cmake to find libraries

I indeed noticed the availability of a cmake module in meson.

> Short: Ok, close this issue.

I will then close this issue.


If you are motivated and have the bandwidth to add meson support to scikit-build, you could look into way for adding an optional dependency to scikit-build that would be installed using `scikit-build[meson]`.

Adding a sample projects could also help demonstrate the use of the optional dependency: https://github.com/scikit-build/scikit-build-sample-projects

In the mean time, I am closing this issue.

**Comment by Nic30** [comment]
> If you are motivated and have the bandwidth

* I am motivated, I do not have time, really, I would like to help but I just can not. If something changes I let you know.
