### ISSUE TITLE
Where are extension modules supposed to be installed?

### ISSUE THREAD

**Issue by eric-wieser** [scikit-build/scikit-build#434]
I'm following the example for a simple extension module, but it's installing in a weird place.

When I use:
```cmake
# simulator
add_library(simulator MODULE
 src/simulatormodule.c
)
python_extension_module(simulator)
install(TARGETS simulator LIBRARY DESTINATION lib)
```

And run `pip3.5 install . --user`, I end up with a file at `~/.local/lib/simulator.cpython-35m-x86_64-linux-gnu.so`. I'd like it to end up at `~/.local/python3.5/site-packages/my_package/simulator.cpython-35m-x86_64-linux-gnu.so`. I believe this is already how things work for `distutils.Extension` objects?

Is there an easy way to make this happen? Could the docs be updated to show this type of usage?

**Comment by thewtex** [comment]
Hello @eric-wieser ,

Does changing the `install` `DESTINATION` from `lib` to `my_package` achieve the desire behavior.

The [scikit-build-sample-projects](https://github.com/scikit-build/scikit-build-sample-projects/blob/e38da6d401dae01e4f2467c7106bff405b18410b/projects/hello-cpp/CMakeLists.txt#L9) may also be helpful.

**Comment by jcfr** [comment]
@eric-wieser Thanks for reaching out. Install destination of a module is expected to corresponds to the python package where it is expected to be imported from.

**Comment by jcfr** [comment]
Do you need any other help to move forward ?

**Comment by eric-wieser** [comment]
> Does changing the `install` `DESTINATION` from `lib` to `my_package` achieve the desire behavior.

Yes, that did solve the problem. Can you explain why `lib` resolves to `~/.local/lib/` but `my_package` resolves to `~/.local/python3.5/site-packages/my_package`?

I'm unblocked, but still a little confused about what happened here.

**Comment by jcfr** [comment]
Since there are no python package called 'lib' specified in setup.py, the files to install that are not associated with a package  and are considered as data files and installed there. See https://docs.python.org/3/distutils/setupscript.html#installing-additional-files

**Comment by eric-wieser** [comment]
Ah, that makes sense - I thought the path looked familiar, that is where I remember `data_files` ending up.

Could you point me to the source within scikit-build that makes that decision? It would be great to have it somewhere within the `scikit-build` docs, if it's not already.

**Comment by jcfr** [comment]
> It would be great to have it somewhere within the scikit-build docs, if it's not already.

:+1: (This is tracked by #436)

This happen here:

https://github.com/scikit-build/scikit-build/blob/dc347b7b3cb25071b1d7df9670146ea14925c750/skbuild/setuptools_wrap.py#L610-L616

The relevant functions are:
* [_collect_package_prefixes](https://github.com/scikit-build/scikit-build/blob/dc347b7b3cb25071b1d7df9670146ea14925c750/skbuild/setuptools_wrap.py#L687-L728)
* [_classify_file](https://github.com/scikit-build/scikit-build/blob/dc347b7b3cb25071b1d7df9670146ea14925c750/skbuild/setuptools_wrap.py#L759-L819) itself called by [_classify_installed_files](https://github.com/scikit-build/scikit-build/blob/dc347b7b3cb25071b1d7df9670146ea14925c750/skbuild/setuptools_wrap.py#L731-L756)

**Comment by eric-wieser** [comment]
Fantastic, I think that resolves any confusion I have left about this. I still remember seeing some weirdness with my CMakeLists not at the root of my source, but I didn't have a good reason to do that anyway, and no longer remember the issue. Thanks!
