### ISSUE TITLE
CMake for manylinux1 Python 3.8

### ISSUE THREAD

**Issue by filipArena** [scikit-build/scikit-build#456]
As per https://github.com/scikit-build/cmake-python-distributions/issues/89 I've built manylinux1 Python 3.8 wheels for cmake:
* [cmake-3.13.2-cp38-cp38-manylinux1_i686.whl](https://drive.google.com/file/d/1Pt_IyOoHb5Rtk7vONKZEMEX-TgqpozJh/view?usp=sharing)
* [cmake-3.13.2-cp38-cp38-manylinux1_x86_64.whl](https://drive.google.com/file/d/1VnN2nGUeyFaAois3tXJW1KO5af3FSzwb/view?usp=sharing)

Can we get them on PyPI?

**Comment by henryiii** [comment]
This should be unneeded now, manylinux1 wheels are provided.

**Comment by filipArena** [comment]
Closing.

**Comment by jcfr** [comment]
Thanks @henryiii and @filipArena for cleaning up the issue tracker :pray:
