### ISSUE TITLE
Dealing with inter-dependent cmake dependencies

### ISSUE THREAD

**Issue by SylvainCorlay** [scikit-build/scikit-build#462]
I am working on using `scikit-build` with a slightly more complex project than the samples provided in `scikit-build-sample-projects` in that the wheel I would like to build would vendor several inter-dependent binary packages (mostly built with cmake).

The `FetchContent` approach of the pybind11 example is interesting but appears to require that the individual cmake files of dependencies also make use of `FetchContent` to define their inter-dependencies.

Is there another means to specify a set of (potentially interdependent) projects?
It seems that what I need is almost checking them out in the right order and building them manually.

**Comment by thewtex** [comment]
@SylvainCorlay `FetchContent` is usually easier to deal with. Another method that is used to build project's is an [`ExternalProject`](https://cmake.org/cmake/help/latest/module/ExternalProject.html) "Superbuild". This is currently [used in the ITK Python Package](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/master/CMakeLists.txt).

**Comment by jcfr** [comment]
The ExternalProject approach used in ITK is more complex to get familiar with at first but has the advantage of keep each dependency "sand-boxed".

**Comment by SylvainCorlay** [comment]
Thanks @thewtex, the ExternalProject "Superbuild" may be what I need!

**Comment by SylvainCorlay** [comment]
@thewtex I am making some strides in building the wheel.

The main obstacle now is how to build non-cmake dependencies such as `OpenSSL`, `ZeroMQ`, and possibly `libuuid`.

**Comment by jcfr** [comment]
>  I am making some strides in building the wheel.

:tada: 

> how to build non-cmake dependencies such a

By default `ExternalProject` assumes the project is using CMake but all steps (configure., build, ...) can be overridden.

Here are examples of external project we used for building the project you referenced:
* OpenSSL: https://github.com/Slicer/Slicer/blob/master/SuperBuild/External_OpenSSL.cmake
* ZeroMQ: https://github.com/commontk/QEmbedIPython/blob/master/CMake/Externals/External_ZeroMQ.cmake

This should probably not be copied verbatim (OpenSSL is specific to Slicer and is handling more that you probably want, and ZeroMQ is old ...)

I linked these here to illustrate how it could be done.

Other examples of non-cmakeified projects:
* https://github.com/Slicer/Slicer/blob/master/SuperBuild/External_tcl.cmake
* https://github.com/Slicer/Slicer/blob/master/SuperBuild/External_tk.cmake

After looking at these, I expect you will have more questions. Do not hesitate to ask :smile:

**Comment by SylvainCorlay** [comment]
@jcfr this is awesome! I was getting around zeromq by using their cmake on linux, but it is not quite the standard way of building it.

Looking into your OpenSSL superbuild!

**Comment by SylvainCorlay** [comment]
@jcfr btw, I am still struggling with the SuperBuild system of Slicer.

@johanmabille and I are looking at basically how to drive the superbuild without modification for another list of projects (essentially OpenSSL and its dependency zlib) although without luck so far.

**Comment by jcfr** [comment]
> I am still struggling with the SuperBuild system of Slicer.

* The build system of Slicer is a two pass system that leverage a module called `ExternalProjectDependency` (see [here](https://cmake-artichoke.readthedocs.io/en/latest/)) that provides functions like `mark_as_superbuild`. It also allows to optionally build against your own  version of any of the dependency while keeping the dependency graph consistent ... 

* For project that do not use CMake, it leverages the module `ExternalProjectForNonCMakeProject` providing convenient function like `ExternalProject_Write_SetBuildEnv_Commands` that allows to write a CMake script later invoked in `CONFIGURE_COMMAND`, `BUILD_COMMAND`

Reading this answer is also useful: http://cmake.3232098.n2.nabble.com/Question-regarding-External-Project-add-and-VTK-tp7587557p7587564.html

To move forward and re-use some of the logic of `External_OpenSSL.cmake`, I suggest to start from a clean plate and pick and choose only the relevant logic.

**Comment by SylvainCorlay** [comment]
Thanks!

**Comment by SylvainCorlay** [comment]
@jcfr we have now a working manylinux wheel, (plus and OSX and a windows build) of xeus-python based on scikit-build - although we have not published it. The source for the scikit-build based project is here: https://github.com/jupyter-xeus/xeus-python-wheel.git

For your information, we use a slightly different way of achieving a superbuild from what you did. Any feedback is welcome.

Closing this issue as resolved for us!
