### ISSUE TITLE
Cygwin Support?

### ISSUE THREAD

**Issue by ax3l** [scikit-build/scikit-build#484]
I am trying to install scikit-build with pip from Cygwin and get the following error message:
```
Unsupported platform: cygwin_nt-10.0-17763. Please contact the scikit-build team.
```

So here I am :)

Platform: GitHub action on `windows-2019` with `Cygwin v3.1.4`.

Proposed PR: #485

**Comment by kingcc** [comment]
There seems to be no problem with merging branch?
