### ISSUE TITLE
Support for Visual Studio 2019?

### ISSUE THREAD

**Issue by mkstoyanov** [scikit-build/scikit-build#496]
Is visual studio 2019 supported and is there a plan to support?

Using the latest scikit-build 0.11.1 and `pip install` works on a system with Visual Studio 2017 and fails on 2019 with long error message about missing 2017. Both tested on Windows 10 Home.

Specifically:
```
python -m pip install Tasmanian --user
```

I have also tried explicitly adding the generator, but it did not help:
```
python -m pip install Tasmanian --user --global-option="-G \"Visual Studio 16 2019\""
python -m pip install Tasmanian --user --global-option='-G "Visual Studio 16 2019"'
python -m pip install Tasmanian --user --global-option='-G Visual Studio 16 2019'
```
Note that pip works fine with VS2017 and the project compilers fine with VS2019 outside of the pip environment.

**Comment by planetmarshall** [comment]
Looks like the linked PR is stale.

**Comment by mkstoyanov** [comment]
The issue becomes more pressing with time as Microsoft pushes 2019 more aggressively and it becomes harder to install previous versions.

**Comment by thewtex** [comment]
Until #526  is integrated, not that you can build in a Visual Studio 2019 Command Prompt.

CC: @jcfr
