### ISSUE TITLE
FindPython support

### ISSUE THREAD

**Issue by henryiii** [scikit-build/scikit-build#506]
I am currently working on adding full CMake 3.12+'s FindPython support to pybind11. Would it be possible to support for FindPython in Scikit-Build's extensions, too?

**Comment by jcfr** [comment]
> Would it be possible to support for FindPython in Scikit-Build's extensions, too?

That makes, for the next year or two, I am wondering if we should support both [FindPython](https://cmake.org/cmake/help/latest/module/FindPython.html) and [FindPythonLibs](https://cmake.org/cmake/help/latest/module/FindPythonLibs.html)

**Comment by henryiii** [comment]
> for the next year or two, I am wondering if we should support both

That is what I'm doing in https://github.com/pybind/pybind11/pull/2370 - for now, if `find_package(Python ...)` has beed called before pybind11, then FindPython's variables and targets are used, otherwise, FindPythonLibs/Interp is used (since it's highly patched by pybind11, it can't be reused from an earlier call in our case).

**Comment by henryiii** [comment]
FindPython is supposed to be able to be copied into a project and used with CMake 3.7+. Otherwise, due to bugs currently being fixed, you need a very recent version of CMake to get parity with FindPythonLibs (3.18.2, possibly). But supporting both seems to be the ideal path, at least for now.

**Comment by henryiii** [comment]
Actually, we need support for FindPython even just in the regular running. Scikit-Build passes PYTHON_EXECUTABLE, PYTHON_VERISON_STRING, PYTHON_INCLUDE_DIR, and PYTHON_LIBRARY; while FindPython needs Python_EXECUTABLE, Python_INCLUDE_DIR, and Python_LIBRARY (Python_VERISON is not actually a hint). For the numbered FindPython's, there's a number there.

How about a new argument, `find_python : bool = False` that you could use to switch to FindPython variables. Maybe even the numbered FindPython could be activated, though you'd have a lot of unused value warnings.

**Comment by hmaarrfk** [comment]
Hmm, i got hit by this because a project versioned a version of sciit-build and noticed it was still an issue today.

 would suggest maybe switching to the new syntax automatically?

```
if(${CMAKE_VERSION} VERSION_LESS "3.12.0")
    # Backward compatibility with older version of cmake
    find_package(PythonInterp)
    set(Python_Interpreter_FOUND ${PYTHONINTERP_FOUND})
    set(Python_EXECUTABLE ${PYTHON_EXECUTABLE})
else()
    find_package(Python COMPONENTS Interpreter)
endif()
```

perhaps.

This is needed for better PyPy support.

**Comment by henryiii** [comment]
No, never select features based on CMake version. That would make it nearly impossible to write code that depends on the functionality such as `Python_EXECTUABLE` vs `PYTHON_EXECUTABLE`, as they would be different based on a user's CMake version. Most (almost all) code would break, since this would suddly change if CMake was > 3.12 (and you might not be able to pin it).

I think an extra argument would be best, with the default eventually changing to "True" instead of "False".

If you need to use it today, though, then it's doable: Just adapt the variables that are being passed through to CMake:

```cmake
# Currently, Scikit-build does not support FindPython, so we convert the
# provided hints ourselves.
if(SKBUILD)
  set(Python_EXECUTABLE "${PYTHON_EXECUTABLE}")
  set(Python_INCLUDE_DIR "${PYTHON_INCLUDE_DIR}")
  set(Python_LIBRARY "${PYTHON_LIBRARY}")
endif()
```

**Comment by hmaarrfk** [comment]
Hmm, i guess I would suggest that code that needs support for pypy probably do the opposite

```
find_package(Python COMPONENTS Interpreter Development)
set(PYTHON_EXECUTABLE "${Python_EXECUTABLE}")
set(PYTHON_INCLUDE_DIR "${Python_INCLUDE_DIR}")
set(PYTHON_LIBRARY "${Python_LIBRARY}")
```

I'm still trying to find all the variables that my particular program needs, but I'll try to report back here.

PyPy support was added to `FindPython` in CMake 3.18, so it would be nice to take advantage of it.

**Comment by henryiii** [comment]
Scikit-build calls CMake with `PYTHON_LIBRARY `, `PYTHON_INCLUDE_DIR`, and `PYTHON_LIBRARY` set to the Python that ran setup.py (on the command line). So if you want to use FindPython in your CMakeLists, you need to adapt those variables so that FindPython doesn't find some random version of Python - it should use exactly what called setup.py.

**Comment by hmaarrfk** [comment]
For more details, I'm trying to adapt zfpy for pypy
https://github.com/LLNL/zfp/tree/develop/python

https://github.com/conda-forge/zfpy-feedstock/pull/11

I feel like i'm missing things for the line `find_package(PythonLibs)` https://github.com/scikit-build/scikit-build/blob/master/skbuild/resources/cmake/FindPythonExtensions.cmake#L248

**Comment by tdegeus** [comment]
Just want to comment with one additional reason to start supporting FindPython (well, other than FindPythonLibs is deprecated ;)) : FindPython includes a NumPy target. So with it, one needs longer use the custom FindNumPy (very nice that it is provided by the way! but still it's nicer to use default CMake features only where possible).

**Comment by hameerabbasi** [comment]
I just saw this and wanted to unify my `CMakeLists.txt` enough for me to start testing it in #712. Anyone is welcome to help review.

**Comment by henryiii** [comment]
Done. :)
