### ISSUE TITLE
ninja: error: unknown target 'install'

### ISSUE THREAD

**Issue by maxgalli** [scikit-build/scikit-build#514]
Hi, I'm writing an extremely simple package structured like follows:

```
.
├── CMakeLists.txt
├── cpp
│   └── greeting
│       ├── inc
│       │   └── hello.h
│       └── src
│           └── hello.cpp
├── pyproject.toml
└── setup.py
```

where:

- ```hello.h``` and ```hello.cpp``` are simple C++ libraries containing just one function
- ```CMakeLists.txt```:
```
cmake_minimum_required(VERSION 3.16)

project(prototype_lib_4_bindings)

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)

add_library(hello_lib SHARED cpp/greeting/src/hello.cpp)
target_include_directories(hello_lib PUBLIC cpp/greeting/inc)
```
- ```setup.py```
```
from skbuild import setup
import setuptools

setup(
    name="try",
    version="0.0.0",
    author="Massimiliano Galli",
    packages=setuptools.find_packages(),
    #cmake_install_dir = 'cmake',
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.6',
)
```
- ```pyproject.toml```
```
[build-system]
requires = ["setuptools", "wheel", "scikit-build", "cmake", "ninja"]
```

When I try to run ```python setup.py install``` I get the following:
```
(...)
-- Build files have been written to: /home/massimiliano/MyProjects/try/_skbuild/linux-x86_64-3.7/cmake-build
ninja: error: unknown target 'install'
Traceback (most recent call last):
  File "/home/massimiliano/python-devel/anaconda3/envs/my_root_env_to_fuck_up/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 589, in setup
    cmkr.make(make_args, env=env)
  File "/home/massimiliano/python-devel/anaconda3/envs/my_root_env_to_fuck_up/lib/python3.7/site-packages/skbuild/cmaker.py", line 507, in make
    os.path.abspath(CMAKE_BUILD_DIR())))

An error occurred while building with CMake.
  Command:
    cmake --build . --target install --config Release --
  Source directory:
    /home/massimiliano/MyProjects/try
  Working directory:
    /home/massimiliano/MyProjects/try/_skbuild/linux-x86_64-3.7/cmake-build
Please see CMake's output for more information.
```
I took a look at the CMake output but I don't find it clearer. Am I doing something wrong and/or is there something that I should check in my conda environment?

Thanks.

**Comment by maxgalli** [comment]
My bad, I didn't specify the ```install``` target in CMakeLists.txt. Closing.

**Comment by marscher** [comment]
I ran into the same issue. How does defining an install target make sense, as it should be given implicitly by pybind_add_module. The module has to be installed next or inside the Python interpreters site-packages / or build directory. This is defined by the interpreter invoking the setup, right?

How did you define your install target?

**Comment by alkorolyov** [comment]
Hi, I ran into similar issue and I had to add this line into my CMakeLists.txt:

`install(TARGETS ${PROJECT_NAME} LIBRARY DESTINATION ${CMAKE_CURRENT_BINARY_DIR})`

Where `${PROJECT_NAME}` is my current target name. Hope it helps.
