### ISSUE TITLE
ARCHFLAGS not picked up to build Apple Silicon arm64 and universal2 wheels

### ISSUE THREAD

**Issue by YannickJadoul** [scikit-build/scikit-build#529]
`cibuildwheel` has rolled out support for Apple Silicon wheels (both `arm64` as well as the combined `universal2`), but scikit-build passes ` -DCMAKE_OSX_ARCHITECTURES=x86_64` to CMake, and thus (silently!) fails to produce wheels with a different architecture.

See also this thread: https://github.com/joerick/cibuildwheel/discussions/579#discussioncomment-345617
CC @henryiii

**Comment by thewtex** [comment]
CC @jcfr

**Comment by henryiii** [comment]
The cmake package needs to be updated to pick up the universal2 official CMake release, as well. I was waiting till Pip supported Universal2 wheels (21.0.1), but now will likely be out for two weeks starting very soon due to the upcoming birth of my daughter.

**Comment by henryiii** [comment]
Cross-ref: https://github.com/scikit-build/cmake-python-distributions/pull/123

**Comment by YannickJadoul** [comment]
Hurray! :balloon: Thanks for taking further care of this, @henryiii :-)
