### ISSUE TITLE
Plan for 0.12

### ISSUE THREAD

**Issue by henryiii** [scikit-build/scikit-build#558]
I'd like to propose that we make a release shortly after #557 and #526 make it in. TODO list:

- [x] #557
- [x] #526
- [x] #568 
 
There are lots of other things we could work on fixing, but these are important features that should be useful (and I want to release before the SciPy talk on pybind11 on Friday, since scikit-build will be mentioned). @jcfr, @thewtex does this sound good?

**Comment by henryiii** [comment]
@jcfr Okay to release? Would you like to or do you want me to?

**Comment by jcfr** [comment]
> Okay to release? Would you like to or do you want me to?

Yess, let's do it :100:  

I suggest you go ahead :pray:  

This will allow us to ensure the full release process can be completed by other core maintainers.

This is really exciting, I beyond grateful for yours, @mayeut and all the other contributors for working on the project.

**Comment by jcfr** [comment]
Looking at the readme file ... the requirement badge is in a "strange" state:

![image](https://user-images.githubusercontent.com/219043/128748836-6f9e7fc2-6449-4a82-bcd6-cc0d8adb5f04.png)


![image](https://user-images.githubusercontent.com/219043/128748813-156c3126-aaac-420e-91bb-29dee799e17d.png)

I am wondering what the `
sphinxcontrib-moderncmakedomain` releases the can't be loaded ...

https://requires.io/github/scikit-build/scikit-build/requirements/?branch=master

**Comment by jcfr** [comment]
> wondering why the `sphinxcontrib-moderncmakedomain` releases the can't be loaded ...

This is was likely a temporary glitch.

![image](https://user-images.githubusercontent.com/219043/128817865-1ff7f08c-1b68-4b2a-aac3-743f10b80d94.png)

**Comment by henryiii** [comment]
@jcfr  The upload failed, it seems the token was not copied in correctly:

```
Warning:  It looks like you are trying to use an API token to authenticate in the package index and your token value does not start with "pypi-" as it typically should. This may cause an authentication error. Please verify that you have copied your token properly if such an error occurs.
```

I'm not a maintainer so I can't upload the wheel & SDist manually.

**Comment by henryiii** [comment]
@jcfr, if you are going to generate and upload a new token, could you name it `pypi_password` instead of `pypa_password` this time? It's technically a password for PyPI, not PyPA. :)

The token will always start with `pypi-`, FYI, as well.

**Comment by jcfr** [comment]
All set. A new secret called `PYPI_PASSWORD` has just been added

![image](https://user-images.githubusercontent.com/219043/128961283-2de59ee8-8406-4cf8-95f4-8f13a643b7bc.png)

**Comment by jcfr** [comment]
I also just invited you to the scikit-build project on pypi. This should help moving forward.
