### ISSUE TITLE
Better setup() defaults

### ISSUE THREAD

**Issue by opadron** [scikit-build/scikit-build#56]
We should add more options in skbuild's `setup()` function to customize more aspects of the build.

**Comment by jcfr** [comment]
Do you have some examples of functionality ?

**Comment by opadron** [comment]
I was just thinking of custom arguments to `setup()` that would mirror the command-line options we've added, like `generator` for `-G` or `num_cores` for `-j`.

**Comment by jcfr** [comment]
Since `generator` and `num_cores` depends on the environment where the wheel is built, I don't think we should support them in setup.py. 

Closing this issue.

Do not hesitate to re-open it, or create a new one with more specific requirements.
