### ISSUE TITLE
Build Support Forum?

### ISSUE THREAD

**Issue by adamgranthendry** [scikit-build/scikit-build#561]
Is there a place to post build questions for specific projects using scikit-build, or should I just place my question here? My question might not be related to scikit-build internals specifically.

**Comment by adamgranthendry** [comment]
In the event it is alright to discuss the question here, please see [this SO post](https://stackoverflow.com/questions/68578252/cmake-build-help-for-pyembree) as it contains the relevant details.

**Comment by jcfr** [comment]
Thanks for raising this :pray: 

We currently have a google group available at https://groups.google.com/g/scikit-build but this is only briefly linked at the bottom for the README (see [here](https://github.com/scikit-build/scikit-build#miscellaneous)) and at the bottom of the documentation (see [here](https://scikit-build.readthedocs.io/en/latest/#resources))

To move forward and more explicit, I suggest:

* adding a "How to get help?" section in the documentation
* discussing the transition from the mailing list to either [GitHub discussion](https://docs.github.com/en/discussions) or a dedicated `scikit-build` category in the [Kitware discourse](https://discourse.kitware.com/). 

Remarks:
* I have experience with discourse to organize discussion of other communities and it has been working well.
* I have no experience with Github discussion platform as it was very recently introduced
* Python itself is using discourse. See https://discuss.python.org/

@henryiii @thewtex @mayeut   Any preferences ?

**Comment by adamgranthendry** [comment]
@jcfr Thank you! I loved your presentation btw! [Scikit-build: A Build System Generator for CPython C/C++/Fortran/Cython Extensions | SciPy 2018](https://www.youtube.com/watch?v=QVkg-cC5oe4) I'm excited to see where this goes and I love to use VTK and ITK!

**Comment by henryiii** [comment]
The nice thing about GitHub discussions is that they are tied to GitHub. I'm happy with discourse, too, though.

**Comment by adamgranthendry** [comment]
@jcfr @henryiii If it helps, the maintainers of `pyvista` created a separate GitHub page called `pyvista-support` specifically for support questions. That way they can keep package development/bugs/specific questions separated from general user questions and get the benefit of using GitHub like you mentioned. Either that, or a separate tag for support questions (vs. bug/feature request/etc.) would be nice!

**Comment by henryiii** [comment]
Isn't that basically just because they pre-dated Discussions? The features of Discussions over issues are they don't get hidden when "answered", and they allow threaded conversations and voting. But mostly, it's a different expectation - issues are generally expected to be answered by package maintainers, while discussions are more open to be answered by all (Social difference).

**Comment by adamgranthendry** [comment]
@henryiii Forgive my ignorance, I wasn't aware "GitHub Discussions" was an actual thing. I'm aware of the "Issue" tracker, "Pull Requests", and "Wiki" page (i.e. the "general tabs"). How do GitHub Discussions work?

**Comment by henryiii** [comment]
We've just opened up Discussions in pybind11 (though likely won't be fully set up till later today). A good example of Discussions looks like https://github.com/ImageMagick/ImageMagick/discussions (just did a quick search). It's like a slightly modified Issues that are more community focused (with the extra above-mentioned features). Issues can be converted into Discussions. Poetry has an active Discussions tab, come to think of it.

**Comment by henryiii** [comment]
I'm currently adding a Discussions link to the issue chooser for pybind11.

**Comment by adamgranthendry** [comment]
@henryiii Oh I like that! It's a new tab. Cool! Ya, I'm definitely open to that option too. I'm flexible.

**Comment by adamgranthendry** [comment]
@henryiii Should I put my current question on the `pybind11` Discussions link, or wait for one to be added here on the `scikit-build` GitHub page?

**Comment by henryiii** [comment]
Unless it's about pybind11, I'd wait till we either open a Discussions here, or a Discourse. Still setting up the pybind11 one. If we open a Discussions here, an existing issue can be converted to a Discussion.

**Comment by adamgranthendry** [comment]
@henryiii @jcfr Thanks again! In the meantime, I joined the corresponding Google forum and posted my question up there. If any of you have time, I would greatly appreciate your help on this!

**Comment by henryiii** [comment]
We have Discussions now, so closing this. :)
