### ISSUE TITLE
Fix arg parsing

### ISSUE THREAD

**Issue by opadron** [scikit-build/scikit-build#57]
Same as #56, but we need to fix the CLI arg parsing logic.

**Comment by jcfr** [comment]
CMake option should exposed using an interface similar to what is done in symengine.py. See https://github.com/symengine/symengine.py/blob/b5d63ebd901030d668b717aeeb8547aa5a14726c/setup.py#L45-L51

**Comment by jcfr** [comment]
Other project integrating CMake:
* https://github.com/pyne/pyne/blob/develop/setup.py

**Comment by jcfr** [comment]
@opadron Could you point out the part of the logic that should be improved along with an example of arguments that would be improperly parsed ? Thanks

**Comment by opadron** [comment]
@msmolens did a good job improving the argument parsing logic.  I would consider this issue resolved.

**Comment by jcfr** [comment]
Great. Thanks for the update.

**Comment by opadron** [comment]
Scratch that, there are still some issues with the argument parsing.

scikit-build should recognize when command line options are given after the subcommand, and just pass them along.

For example,

`python setup.py sdist --help` causes the scikit-build logic to short-circuit straight to the main help output.

Instead, it should skip only the CMake-level build, and let the subcommand provide its help output.

**Comment by opadron** [comment]
Scratch that, again!  It looks like the correct output is produced. I just didn't notice the subcommand help on the bottom.

Sorry for the noise!
