### ISSUE TITLE
Support CMAKE_ARGS

### ISSUE THREAD

**Issue by henryiii** [scikit-build/scikit-build#588]
Some tools (conda) set CMAKE_ARGS; ideally I think that should be automatically supported. It's also really nice to have environment variable methods to pass things through, since modern build systems do not have direct access to the setup.py call.

I'd propose something like:

```python
if "CMAKE_ARGS" in os.environ:
    cmake_args += [arg for arg in os.environ["CMAKE_ARGS"].split(" ") if arg]
```

Might need to handle quotes. See https://github.com/tdegeus/QPot/pull/36 and https://github.com/pybind/cmake_example/pull/58

**Comment by tdegeus** [comment]
One thing I found in https://github.com/conda-forge/qpot-feedstock/pull/31 is that currently scikit-build fails if `DCMAKE_INSTALL_PREFIX` is specified. So currently I'm doing 
```python
cmake_args = []

if "CMAKE_ARGS" in os.environ:
    args = list(filter(None, os.environ["CMAKE_ARGS"].split(" ")))
    if len(args) > 0:
        cmake_args += [arg for arg in args if len(arg.split("DCMAKE_INSTALL_PREFIX")) == 1]

setup(
    ...
    cmake_args = cmake_args,
)
```

**Comment by henryiii** [comment]
Looks like https://github.com/conda-forge/ctng-compiler-activation-feedstock/blob/6290f55b73a887086b0efe0cdb32553646696a8a/recipe/activate-gcc.sh#L137-L149 is where this is set. I'd like to see if conda-forge would be interested in setting `SKBUILD_CONFIGURE_OPTIONS` here as well; the `SKBUILD_CONFIGURE_OPTIONS` could also avoid the path setting.

**Comment by tdegeus** [comment]
If `SKBUILD_CONFIGURE_OPTIONS` does already do exactly what `CMAKE_ARGS` would do, then there is no need for an extra variable (one can just copy). However:
* I would propose to document this variable clearly, currently it remains completely undocumented.
* I would propose to add a scikit-build section to https://conda-forge.org/docs/maintainer/knowledge_base.html
* Personally I find the name a bit confusing: `CONFIGURE_OPTIONS` could for me just as easily be meant for the Python side as for the CMake side.

**Comment by tdegeus** [comment]
Is there any update on this. I still have this in my build script:

**Comment by henryiii** [comment]
I think we should propose to add `SKBUILD_CONFIGURE_OPTIONS` to conda-forge. I just need to figure out where. :)

I'm not fond of the name, it's a bit long and not that descriptive, but it's not awful. Though including it in conda-forge would likely lock it in even more.

The alternative option would be to also accept CMAKE_ARGS, but that might be too easy to trigger? Of course, if CMake natively supported something, that would be nice.

**Comment by henryiii** [comment]
I have two ideas. One would be to export CMAKE_ARGS to SKBUILD_CONFIGURE_OPTIONS in the activation script(s) for the scikit-build-feedstock. Unfortunately, we'd need to be sure it activated after the CMAKE_ARGS is finalized, as I think other activation scripts can add to CMAKE_ARGS.

The other idea would be to enable `CMAKE_ARGS`, but let `SKBUILD_CONFIGURE_OPTIONS` override it. That way, if `CMAKE_ARGS` was broken or you wanted full control, you could define `SKBUILD_CONFIGURE_OPTIONS`.

Given the way conda-forge handles `CMAKE_ARGS`, I think option 2 might be necessary. I wonder if we could enable it under an experimental flag for the next release, then fully enable it if it works well?
