### ISSUE TITLE
python dylib is linked in when cross-compiling

### ISSUE THREAD

**Issue by isuruf** [scikit-build/scikit-build#589]
When cross compiling for OSX, `libpython3.9.dylib` is linked to extension modules
which results in a segfault when the python executable is linked to a static libpython.

Happens at https://github.com/conda-forge/python-blosc-feedstock

**Comment by isuruf** [comment]
Also an issue with https://github.com/conda-forge/slycot-feedstock/issues/34

**Comment by isuruf** [comment]
@henryiii, can we add a reasonable workaround when `CROSSCOMPILING` turned on? (i.e. assume that dynamic_lookup is available on macOS if cross compiling)

**Comment by henryiii** [comment]
Sure, I'd be fine to add a workaround. I'm hoping to rewrite this entirely eventually (https://iscinumpy.dev/post/scikit-build-proposal/), but that won't happen until later this year or next.

**Comment by henryiii** [comment]
Could you make the PR, or would you like me to do it? We'll probably be getting a small 0.13 release out for scikit-build in the near future.
