### ISSUE TITLE
Parse setuptools extras as cmake args

### ISSUE THREAD

**Issue by gsakkis** [scikit-build/scikit-build#608]
I'd like to be able to specify CMAKE flags (ab)using setuptools "extras" (typically used for optional dependencies), something along these lines (pseudocode):

```
# setup.py
from skbuild import setup

# can i get "extras" here? how?
FOO_ENABLED = "ON" if "foo" in extras else "OFF"
BAR_ENABLED = "ON" if "bar" in extras else "OFF"

setup(
    name="mypkg",
    cmake_args=[
        f"-DWITH_FOO:BOOL={FOO_ENABLED}",
        f"-DWITH_BAR:BOOL={BAR_ENABLED}"
    ],
   ...
)
```

Then I can install `mypkg` with `foo` and `bar` with `pip install mypkg[foo,bar]`

Is this possible?
- If yes, how?
- If not, what alternative(s) is/are there?

**Comment by henryiii** [comment]
Extras can only be used to change the dependencies. You can't perform any logic with them - they just fill a metadata slot.
