### ISSUE TITLE
Python library not found when using recent setuptools with pypy

### ISSUE THREAD

**Issue by rkaminsk** [scikit-build/scikit-build#618]
It seems like there is a problem using pypy 7.3.7 together with scikit-build and setuptools version 64.2.0 because cmake is called with `-DPYTHON_LIBRARY=`. Using the setuptools version 59.4.0, everything works and a correct library path is passed. Does anyone know about this problem?

I originally reported the problem in the manylinux project pypa/manylinux#1246 where I also attached log files.

**Comment by rkaminsk** [comment]
I looked a bit around and found the problem in `scikit-build/skbuild/cmaker.py` in function `get_python_library`. With newer setuputils versions, function `du_sysconfig.get_config_var('LIBDIR')` does not behave as before anymore:

```python
>>> import distutils.sysconfig as du_sysconfig
>>> import sysconfig
>>> du_sysconfig.get_config_var('LIBDIR')
'/build_dir/pypy-c-jit-linux-x86-64/build/bin'
>>> sysconfig.get_config_var('LIBDIR')
'/snap/pypy3/95/bin'
```

The above code ran on Ubunutu with pypy installed via snap but something similar happens when running in a manylinux container to build platform-specific wheels.

I think it would be relatively easy be fixed by adding both libdirs to the candidates cross-product. What do you think?

**Comment by mlasch** [comment]
I looked a bit around on this topic, because I have also an issue in this area (#621). The `distutils` module is deprecated and will be removed from the standard library in Python 3.12, see [PEP632](https://www.python.org/dev/peps/pep-0632/). I guess there needs to be a solution based on `sysconfig` only.
The `sysconfig` module was introduced with Python 3.2 so backwards compatibility should be fairly well guaranteed.

**Comment by rkaminsk** [comment]
> I looked a bit around on this topic, because I have also an issue in this area (#621). The `distutils` module is deprecated and will be removed from the standard library in Python 3.12, see [PEP632](https://www.python.org/dev/peps/pep-0632/). I guess there needs to be a solution based on `sysconfig` only. The `sysconfig` module was introduced with Python 3.2 so backwards compatibility should be fairly well guaranteed.

It would be relatively easy to make this future proof by conditionally importing the `distutils.sysconfig` module. (At least in the one file of the project I looked at.) We should probably wait for the project maintainers for some feedback, though.

**Comment by mlasch** [comment]
> It would be relatively easy to make this future proof by conditionally importing the distutils.sysconfig module.

I think distutils is not even needed anymore.

> We should probably wait for the project maintainers for some feedback, though.

I agree.

In the meantime I made a "works on my machine" solution, which I did not clean up yet, because I was not sure if this will work in all cases: https://github.com/mlasch/scikit-build/commit/67e26972dd4b80ddf709316dd0560f4f9485e25d. @rkaminsk maybe you want to have a look if this will also solve your problem.

**Comment by rkaminsk** [comment]
I opened a PR, too. My idea was to be 100% backwards compatible. See #620, which is also mentioned above. This really depends on the maintainers. It looks a bit like they want to still support very old python versions.

**Comment by henryiii** [comment]
Old Python versions (<3.6) will be dropped soon. Possibly/probably after the next release. Target was Jan 1 but a release is needed first.

Currently trying to fix an issue with setuptools 60.2 breaking our tests. Once CI comes back up will be easier to field PRs.

**Comment by robtaylor** [comment]
I just hit this issue on VERSION="20.04.3 LTS (Focal Fossa)". Would love to see a fix!

**Comment by henryiii** [comment]
I think the latest master should work, since #620 and #630 are merged. Working on #628 before a release.

**Comment by robtaylor** [comment]
And still happens with head:
```
In [1]: from skbuild import cmaker

In [2]: cmaker.CMaker.get_python_library("3.9")
Out[2]: 'libpython3.9.a'
```

**Comment by robtaylor** [comment]
```
ipdb>
> /home/robtaylor/.local/lib/python3.9/site-packages/skbuild/cmaker.py(515)get_python_library()
    513             )
    514
--> 515             for candidate in candidates:
    516                 if os.path.exists(candidate):
    517                     # we found a (likely alternate) libpython

ipdb> for i in candidates:
    print(i)
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/python39.lib
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/python3.9.lib
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/python.lib
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/python39.so
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/python3.9.so
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/python.so
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/python39.a
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/python3.9.a
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/python.a
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/libpython39.lib
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/libpython3.9.lib
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/libpython.lib
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/libpython39.so
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/libpython3.9.so
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/libpython.so
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/libpython39.a
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/libpython3.9.a
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/libpython.a
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/python39.lib
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/python3.9.lib
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/python.lib
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/python39.so
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/python3.9.so
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/python.so
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/python39.a
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/python3.9.a
/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/python.a
```

**Comment by robtaylor** [comment]
Fix suggested in #632

**Comment by henryiii** [comment]
```console
$ docker run --rm -it ubuntu:20.04
$ apt update && apt install -y python3.9-dev python3.9-venv
$ python3.9 -m venv --upgrade .venv
$ .venv/bin/pip install -U setuptools scikit-build
$ .venv/bin/python3.9 -c 'from skbuild import cmaker; print(cmaker.CMaker.get_python_library("3.9"))'
libpython3.9.a
```

This sequence works for 3.8.

**Comment by robtaylor** [comment]
> ```
> $ docker run --rm -it ubuntu:20.04
> $ apt update && apt install -y python3.9-dev python3.9-venv
> $ python3.9 -m venv --upgrade .venv
> $ .venv/bin/pip install -U setuptools scikit-build
> $ .venv/bin/python3.9 -c 'from skbuild import cmaker; print(cmaker.CMaker.get_python_library("3.9"))'
> libpython3.9.a
> ```
> 
> This sequence works for 3.8.

it should be returning `'/usr/lib/x86_64-linux-gnu/libpython3.9.so'` no?

**Comment by henryiii** [comment]
I can verify that this works with #632:

```console
# .venv/bin/python3.9 -c 'from skbuild import cmaker; print(cmaker.CMaker.get_python_library("3.9"))'
/usr/lib/x86_64-linux-gnu/libpython3.9.so
```

**Comment by rkaminsk** [comment]
Getting this path is super messy. Now, they started to add the multi-arch subdirectory to the `LIBDIR`. It just seems random. I wish there would be one standard way...

PS: I have seen now two more recent Python versions where the path could be determined using `LIBDIR`+`LDLIBRARY`. Maybe this is becoming the standard way?

**Comment by robtaylor** [comment]
@henryiii any near-term plans for a release with this fix in? Thanks!

**Comment by henryiii** [comment]
Yes, I was hoping to get #634, #641, and #477 in. If @jcfr doesn't have time to do a review very soon, though, I think we should go ahead and push 0.13, say later today or tomorrow, and then work on 0.14 in the near future with those. I'd also like to work on cleaning out some distutils and see if it's possible to better support setup.cfg, but that's always been 0.14 target material.

**Comment by robtaylor** [comment]
Awesome! thank you :)

**Comment by henryiii** [comment]
Those are in and released a while ago, hopefully this works now. :)
