### ISSUE TITLE
GCC found on Windows if Ninja MSVC 2019+ not present

### ISSUE THREAD

**Issue by henryiii** [scikit-build/scikit-build#636]
If only non-Ninja (2017 and before) MSVC's are present, a GCC from chocolaty will be found by the ninja 2022 search, since it's not actually including the 2022 or even MSVC in the search, but just checking vanilla Ninja. We should enforce the one we are looking for is also the one found.

We might be able to use this: https://discourse.cmake.org/t/feature-request-give-me-a-way-to-specify-the-msvc-toolset-when-using-g-ninja/1332/8

_Originally posted by @henryiii in https://github.com/scikit-build/scikit-build/issues/631#issuecomment-1022355519_

**Comment by jcfr** [comment]
The class `CMakeVisualStudioCommandLineGenerator` is expected to ensure the proper env is setup when using Ninja.

See https://scikit-build.readthedocs.io/en/latest/skbuild.platform_specifics.html#skbuild.platform_specifics.windows.CMakeVisualStudioCommandLineGenerator

I suspect the underlying logic need to be improved to work with recent Visual Studio

**Comment by segevfiner** [comment]
Hit here: https://github.com/segevfiner/cyminhook/runs/5051704068?check_suite_focus=true 😢

**Comment by henryiii** [comment]
Fixed in 0.13.1!
