### ISSUE TITLE
ninja not found, fallback on make selected

### ISSUE THREAD

**Issue by tdegeus** [scikit-build/scikit-build#666]
On conda `ninja` in consistently not found on `unix`, requiring `make  # [unix]` which I don't think should be needed. See e.g. https://github.com/conda-forge/gmatelastoplasticqpot-feedstock/pull/35

**Comment by tdegeus** [comment]
Here is a fresh log : https://github.com/conda-forge/gmatelastoplasticqpot-feedstock/pull/38

**Comment by henryiii** [comment]
I think this has been worked out (and the conda recipe is better now, slightly) - the problem was that conda-build hardcodes in CMAKE_GENERATOR with makefiles.
