### ISSUE TITLE
scikit-build clobbers the visibility of non-local symbols

### ISSUE THREAD

**Issue by vyasr** [scikit-build/scikit-build#668]
The changes implemented in #299 to ensure that Python extension module init symbols are global also mark all other symbols as local. This change, which I assume is to reduce the footprint of Cython symbols in the symbol table, has the unfortunate side effect of overriding any visibility attributes that library developers have attached to their own symbols. Is there any way to use a more targeted visibility override in the linker script defined [here](https://github.com/scikit-build/scikit-build/blob/master/skbuild/resources/cmake/FindPythonExtensions.cmake#L344)?

**Comment by vyasr** [comment]
As an example from rapidsai/rmm#976, here is the difference in a particular symbol when compiled before and after overriding the linker script linked above:
```
(rapids) rapids@compose:~/rmm/python/tmp$ diff <(readelf -s memory_resource_new.cpython-38-x86_64-linux-gnu.so | c++filt) <(readelf -s memory_resource_old.cpython-38-x86_64-linux-gnu.so | c++filt) | grep _ZGVZN3rmm2mr6detail30str
<    460: 0000000000000018     8 TLS     UNIQUE DEFAULT   20 _ZGVZN3rmm2mr6detail30str
<   1202: 0000000000000000     8 TLS     UNIQUE DEFAULT   20 _ZGVZN3rmm2mr6detail30str
<    770: 0000000000000000     8 TLS     UNIQUE DEFAULT   20 _ZGVZN3rmm2mr6detail30str
<   1429: 0000000000000018     8 TLS     UNIQUE DEFAULT   20 _ZGVZN3rmm2mr6detail30str
>    722: 0000000000000000     8 TLS     LOCAL  DEFAULT   20 _ZGVZN3rmm2mr6detail30str
>   1261: 0000000000000018     8 TLS     LOCAL  DEFAULT   20 _ZGVZN3rmm2mr6detail30str
```

**Comment by jcfr** [comment]
@vyasr  Working on adding a scikit-build test and also updating one of the sample project [^1], could you point me to rmm symbols expected to be externally resolved ? (I wasn't able to identify where `_ZGVZN3rmm2mr6detail30str` came from)

In addition of [rmm::mr::detail::get_map / device_id_to_resource](https://github.com/rapidsai/rmm/blob/17bdbcbb29eaa1a1706b228f92b73d058c515e28/include/rmm/mr/device/per_device_resource.hpp#L97-L102), which other ones are also expected to be globally visible ?


[^1]: https://github.com/scikit-build/scikit-build-sample-projects/tree/master/projects

**Comment by jcfr** [comment]
It turns out that the additional parameter `--wide` should be passed to `readelf` to avoid truncation of symbols.

Here is the output posted above with fully demangled symbols

```bash
$ diff \
  <(readelf -s --wide memory_resource_new.cpython-38-x86_64-linux-gnu.so | c++filt) \
  <(readelf -s --wide memory_resource_old.cpython-38-x86_64-linux-gnu.so | c++filt) \
  | grep "guard variable for rmm::mr::detail::stream"
```

```diff
<    460: 0000000000000018     8 TLS     UNIQUE DEFAULT   20 guard variable for rmm::mr::detail::stream_ordered_memory_resource<rmm::mr::fixed_size_memory_resource<rmm::mr::device_memory_resource>, rmm::mr::detail::fixed_size_free_list>::get_event(rmm::cuda_stream_view)::event_tls
<   1202: 0000000000000000     8 TLS     UNIQUE DEFAULT   20 guard variable for rmm::mr::detail::stream_ordered_memory_resource<rmm::mr::pool_memory_resource<rmm::mr::device_memory_resource>, rmm::mr::detail::coalescing_free_list>::get_event(rmm::cuda_stream_view)::event_tls
<    770: 0000000000000000     8 TLS     UNIQUE DEFAULT   20 guard variable for rmm::mr::detail::stream_ordered_memory_resource<rmm::mr::pool_memory_resource<rmm::mr::device_memory_resource>, rmm::mr::detail::coalescing_free_list>::get_event(rmm::cuda_stream_view)::event_tls
<   1429: 0000000000000018     8 TLS     UNIQUE DEFAULT   20 guard variable for rmm::mr::detail::stream_ordered_memory_resource<rmm::mr::fixed_size_memory_resource<rmm::mr::device_memory_resource>, rmm::mr::detail::fixed_size_free_list>::get_event(rmm::cuda_stream_view)::event_tls
>    722: 0000000000000000     8 TLS     LOCAL  DEFAULT   20 guard variable for rmm::mr::detail::stream_ordered_memory_resource<rmm::mr::pool_memory_resource<rmm::mr::device_memory_resource>, rmm::mr::detail::coalescing_free_list>::get_event(rmm::cuda_stream_view)::event_tls
>   1261: 0000000000000018     8 TLS     LOCAL  DEFAULT   20 guard variable for rmm::mr::detail::stream_ordered_memory_resource<rmm::mr::fixed_size_memory_resource<rmm::mr::device_memory_resource>, rmm::mr::detail::fixed_size_free_list>::get_event(rmm::cuda_stream_view)::event_tls

```

**Comment by jcfr** [comment]
From https://gcc.gnu.org/wiki/Visibility

> Some people may suggest that GNU linker version scripts can do just as well. Perhaps for C programs this is true, but for C++ it cannot be true - unless you laboriously specify each and every symbol to make public (and the complex mangled name of it), you must use wildcards which tend to let a lot of spurious symbols through. And you have to update the linker script if you decide to change names to the classes or the functions. In the case of the library above, the author couldn't get the symbol table below 40,000 symbols using version scripts. Furthermore, using linker version scripts doesn't permit GCC to better optimise the code. 

This means we should look into removing the use of `-Wl,--version-script` from `FindPythonExtensions.cmake`:

https://github.com/scikit-build/scikit-build/blob/bb14ecba0b31d1ffad7de24d565229a62a835dfb/skbuild/resources/cmake/FindPythonExtensions.cmake#L340-L349
