### ISSUE TITLE
Update setup.py to use setuptools

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#68]
* http://docs.python-guide.org/en/latest/writing/structure/#structure-of-the-repository
* http://setuptools.readthedocs.io/en/latest/setuptools.html
* https://github.com/kennethreitz/samplemod/blob/master/setup.py

**Comment by thewtex** [comment]
Also, update the configuration so the standard `python setup.py test` works

* http://nose.readthedocs.io/en/latest/setuptools_integration.html?highlight=python%20setup.py%20test
