### ISSUE TITLE
SKBUILD_CONFIGURE_OPTIONS not picked up in 0.14.0

### ISSUE THREAD

**Issue by RUrlus** [scikit-build/scikit-build#694]
Hi @henryiii,

It looks like cmake configure options are not longer being picked up when set through the env variable `SKBUILD_CONFIGURE_OPTIONS`.
e.g.
```bash
SKBUILD_CONFIGURE_OPTIONS="-DDIPTEST_ENABLE_OPENMP=ON" pip install diptest --no-binary=diptest
```
no longer works on 0.14.0 but does on 0.13.1.

I didn't see anything related to this in the change documentation but I may have missed something.

**Comment by henryiii** [comment]
Not supposed to have changed. The change was that if `SKBUILD_CONFIGURE_OPTIONS` was unset, then `CMAKE_ARGS` is allowed.

**Comment by henryiii** [comment]
https://github.com/scikit-build/scikit-build/blob/9ae49a2527d8dbe563d7a55f220da7c278aa94af/skbuild/cmaker.py#L289

🤦

**Comment by henryiii** [comment]
I'll make a PR as soon as I have our CI up again (#691).
