### ISSUE TITLE
Failing to pass arguments to `pip install .` builds on Windows

### ISSUE THREAD

**Issue by bnavigator** [scikit-build/scikit-build#705]
Hi,

I am trying to remove deprecated `python setup.py install` calls in our CI and building instructions for Slycot:
https://github.com/python-control/Slycot/pull/173

I am unable to pass scikit-build command line arguments through pip in a conda-build recipe for Windows.

This one works:

```batch
set BLAS_ROOT=%PREFIX%
set LAPACK_ROOT=%PREFIX%

"%PYTHON%" setup.py install -G "NMake Makefiles" -DBLA_VENDOR=Generic

if errorlevel 1 exit 1
```

On Unix-like systems I can do:
```sh
export SKBUILD_CONFIGURE_OPTIONS="-DBLA_VENDOR=Generic"
$PYTHON -m pip install -v . --no-build-isolation --global-option='--generator="Unix Makefiles"'
```

How do I set the generator for pip builds on Windows?
```batch
set "SKBUILD_CONFIGURE_OPTIONS=-DBLA_VENDOR=Generic"
"%PYTHON%" -m pip install . --no-build-isolation --global-option="--generator=NMake Makefiles" -vv
```
doesn't do the trick.

I also reconn that using `pip --global-option`, `--build-option` and so on are actually not sustainable.  (https://github.com/pypa/pip/pull/9774, https://github.com/pypa/pip/issues/9769)

So how do I specify the generator from the CLI or environment for a modern Python installation without setup.py on all platforms?

**Comment by henryiii** [comment]
Yes, the general method is to use environment variables, as that works everywhere, and we try to ensure standard variables work.
