### ISSUE TITLE
Build type always ends up on default "Release"

### ISSUE THREAD

**Issue by orliac** [scikit-build/scikit-build#749]
Hi,
In https://github.com/scikit-build/scikit-build/blob/master/skbuild/setuptools_wrap.py#:~:text=%23%20Since%20CMake%20arguments,%5D%20%2B%20cmake_args
should
```
cmake_args = skbuild_kw["cmake_args"] + cmake_args
```
rather be
```
cmake_args = cmake_args + skbuild_kw["cmake_args"]
```
Otherwise, regardless of the content of environment variable `CMAKE_ARGS` or of the setup configuration:
```
skbuild.setup(
    ...
    cmake_args=['-DCMAKE_BUILD_TYPE:STRING=Abc123']
    ...
)
```
scikit-build always ends up with a `cmake_args` with a trailing `'-DCMAKE_BUILD_TYPE:STRING=Release'` (coming from https://github.com/scikit-build/scikit-build/blob/master/skbuild/setuptools_wrap.py#:~:text=%3DFalse)-,parser.add_argument(,),-parser.add_argument), hence discarding whatever build type the user is passing.

**Comment by henryiii** [comment]
I think this will be a configuration point for scikit-build-core. There's another option, using the cache init file, but that's still scikit-build-core only at the moment (but I might backport that soon).

**Comment by eguiraud** [comment]
Hi, while this issue is unresolved what's the "blessed" way to get a `RelWithDebInfo` or `Debug` build?

**Comment by henryiii** [comment]
Scikit-build-core supports `cmake.build-type = "Release"` as a configuration option.

**Comment by eguiraud** [comment]
Ah I didn't know about the rewrite, thanks. Unfortunately the project I'm trying to hack on (not my project) is using scikit-build.

**Comment by orliac** [comment]
Thanks for the fix!
