### ISSUE TITLE
Editable installation broken for pip>=21.3

### ISSUE THREAD

**Issue by qnzhou** [scikit-build/scikit-build#770]
Tested with [scikit-build-sample-projects](https://github.com/scikit-build/scikit-build-sample-projects).

Steps to reproduce:
```sh
$ pip install pip==21.3  # or any version >=21.3.
$ git clone git@github.com:scikit-build/scikit-build-sample-projects.git
$ cd scikit-build-sample-prjects/projects/hello-cmake-package
$ pip install -v -e .  # from the print out, it is apparent that cmake is never invoked by the build.
$ python -c "import hello"  # Result in "ModuleNotFoundError: No module named 'hello._hello'"
```

Rolling back pip to 21.2.4 results in the correct bahavior.

**Comment by henryiii** [comment]
You can use `SETUPTOOLS_ENABLE_FEATURES=legacy-editable` for now. In order to support the new editable mode, we have to build a mapping of input to output files, which will only be possible with CMake 3.15+ as a requirement (and is being worked on in scikit-build-core, the rewrite). Dup of #740.

**Comment by qnzhou** [comment]
Thanks Henry!  Closing this as it is duplicate of #740 !
