### ISSUE TITLE
Move babel and pen tests to separate repository.

### ISSUE THREAD

**Issue by thewtex** [scikit-build/scikit-build#78]
These should be moved out of the internal test suite since they have third
party dependencies that are not satisfied by requirements-dev.txt. They should
still be tested in the project CI tests.

**Comment by jcfr** [comment]
:+1:

**Comment by jcfr** [comment]
Few things to consider:
* Re-use continuous integration scripts. See #46
* Make use of tox

**Comment by thewtex** [comment]
Running `nosetests`, `pytest`, or `tox` should work out of the box on any vanilla system.

**Comment by opadron** [comment]
I don't currently have permission to create new repositories under the scikit-build organization.

**Comment by jcfr** [comment]
> don't currently have permission to create new repositories

You should now be able to create repo. Which repo names are you thinking ?

**Comment by opadron** [comment]
I was thinking something like "scikit-build-sample-projects".

**Comment by jcfr** [comment]
Makes sense, could you consider extracting the history ?

Run the script from the parent folder of `scikit-build` project checkout

```bash
mkdir scikit-build-sample-projects && cd scikit-build-sample-projects && git init --bare  && \
SCIKIT_BUILD_SAMPLE_PROJECTS_DIR=$(pwd) && \
cd .. && \
cd scikit-build && \
git subtree split --prefix=tests/samples/ -b scikit-build-sample-projects && \
git remote add local-scikit-build-sample-projects file://$SCIKIT_BUILD_SAMPLE_PROJECTS_DIR && \
git push local-scikit-build-sample-projects scikit-build-sample-projects:refs/heads/master
```

Then put on github:

```bash
cd ../scikit-build-sample-projects
git remote add origin git@github.com:scikit-build/scikit-build-sample-projects.git
git push origin master
```

Adapted from [command line memo#Git](https://docs.google.com/document/d/1aL7jPV6d7cVtyuoxyIciPRPX-LFn4vrupbxdmf4Nyww/edit#heading=h.v0qhbfr00xc8)

**Comment by jcfr** [comment]
Sample project removed in https://github.com/scikit-build/scikit-build/commit/2a88ca02cb60c4946a28f2693bbac6c9564ddea9

@opadron Could you reference the current location of these sample projects ? If not already pushed somewhere, could you publish them on `scikit-build/scikit-build-sample-projects` project ? 

Thanks

**Comment by opadron** [comment]
[done](https://github.com/scikit-build/scikit-build-sample-projects)
We should move further discussion to that repo.

**Comment by jcfr** [comment]
Thanks
