### ISSUE TITLE
Yank 0.16.0

### ISSUE THREAD

**Issue by henryiii** [scikit-build/scikit-build#788]
@jcfr, @thewtex I don't have manage permission on the PyPI project - I can't yank 0.16.0. It is missing python_requires, so it's breaking Python 2 & 3.5, which was not the intention. We need to yank the release to fix Python 2.7 & 3.5. 3.6+ has been fixed by 0.16.1.

**Comment by thewtex** [comment]
@henryiii 0.16.0 successfully yanked and permissions for your account updated for the future.
