### ISSUE TITLE
Update mailing list to be readonly and redirect to GitHub Discussions

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#800]
See https://groups.google.com/g/scikit-build

* [x] Draft last message and auto-reponse
* [x] Send a last message indicating we are now using GitHub discussions
  - :heavy_check_mark: See https://groups.google.com/g/scikit-build/c/jU7-EvvMPb8
* [x] <s>Engage with @Kitware sysadmin to</s> setup auto-reponse and mark the list as readonly
  - :heavy_check_mark: Posting has been disabled for everyone expect the owner
  - :x: Since `Auto-replies` is not available for Google groups created outside an organization and setting up gmail filter leveraging sending of template is not working[^1], this has not been implemented.

[^1]: Email received from a google groups have the `Return-Path:` header set to a value like `<groupname>+bnc<31-uppercase-letters>@googlegroups.com` that is picked up by the gmail filter (instead of the value associated with the `Reply-To:` field.

**Comment by jcfr** [comment]
### Last message to send

```
After many years, we are now ready to move away from the mailing list.

Indeed, to better help the community, we are moving forward with the Discussions board available in the scikit-build GitHub organization.

See https://github.com/orgs/scikit-build/discussions

We believe that transitioning away from the mailing list and adopting the GitHub discussions will provide a more integrated platform enabling us to more effectively engage with the community.

The mailing list will be updated to be read-only with an auto-response referencing the GitHub discussion board.

Note that we are actively working on scikit-build and will soon be releasing scikit-build 1.0, to learn about the details, see https://github.com/scikit-build/scikit-build/wiki#roadmap
```

### Auto-response message

```
Thanks for reaching out !

To better help you, we invite you to post your questions on the Discussions board available on the scikit-build GitHub organization.

See https://github.com/orgs/scikit-build/discussions
```

**Comment by jcfr** [comment]
@henryiii Let me know when you are done updating the roadmap and I will move forward with the mailing-list updates

**Comment by henryiii** [comment]
https://github.com/scikit-build/scikit-build/wiki look fine?

**Comment by henryiii** [comment]
Maybe "plan" instead of "soon" - it's probably 3+ months out at least; we need the setuptools extension in place before releasing scikit-build 1.0.

**Comment by henryiii** [comment]
Scikit-build-core 0.1.0 is out.

**Comment by jcfr** [comment]
scikit-build Google groups settings have been updated:

| Before | After |
|--|--|
| ![image](https://user-images.githubusercontent.com/219043/207785235-4f7fb96e-b84f-4dab-8b03-c02716859c42.png) | ![image](https://user-images.githubusercontent.com/219043/207785538-b2c85f9a-f916-4206-a313-591682211242.png) |
| ![image](https://user-images.githubusercontent.com/219043/207785864-9a7d1290-6ae7-4b8b-9635-4f94b30f7243.png) | ![image](https://user-images.githubusercontent.com/219043/207785772-823bff6a-6e6c-46e6-979b-2bf083c2b65b.png) |
