### ISSUE TITLE
`error LNK2019: unresolved external symbol` during Windows build

### ISSUE THREAD

**Issue by oraluben** [scikit-build/scikit-build#803]
Hi there, I met this issue while migrating one project using scikit-build to support windows and I kept seeing this linker error:
```
    library.cpp.obj : error LNK2019: unresolved external symbol _Py_NoneStruct referenced in function "struct _object * __cdecl PyInit_skbuild_test(void)" (?PyInit_skbuild_test@@YAPEAU_object@@XZ)
    skbuild_test.cp311-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
```

It seems to be a bug in my code (otherwise all Windows build by skbuild will fail) but I have no clue about the reason.

I've created this simple reproducer with one source file and Github Actions failed as local.
repro: https://github.com/oraluben/skbuild-test
GA log: https://github.com/oraluben/skbuild-test/actions/runs/3536759415/jobs/5936111933

Would you mind take a look?

**Comment by oraluben** [comment]
I've spotted the root case but still don't understand very well:
https://github.com/oraluben/skbuild-test/blob/d22a862682919149e0a94770821d9678298586a5/CMakeLists.txt#L8

**Comment by oraluben** [comment]
Not related to skbuild, switch to Python Discourse: https://discuss.python.org/t/py-build-core-causes-different-link-time-behavior-on-windows-and-linux/21362

**Comment by henryiii** [comment]
Why are you activating the private, internal API? https://devguide.python.org/developer-workflow/c-api/. It is not supported for anything past building CPython itself.

FYI, scikit-build-core has just been released. If you are doing something new, it might be worth trying.

**Comment by oraluben** [comment]
Thanks for your reply!

> Why are you activating the private, internal API? https://devguide.python.org/developer-workflow/c-api/. It is not supported for anything past building CPython itself.
The project is a small reproducer reduced from a project that relies on CPython internal API.

> FYI, scikit-build-core has just been released. If you are doing something new, it might be worth trying.
Thanks! I'll investigate.
