### ISSUE TITLE
Allow architecture to be specified in other ways.

### ISSUE THREAD

**Issue by vespakoen** [scikit-build/scikit-build#809]
Hi there!

I am trying to integrate scikit-build into a project, which is mosly working fine.
The problem I am having is that, when cross compiling on windows I cannot change the architecture.

The architecture is automatically detected, and can be changed by providing the -A flag to the scikit-build options. (e.g. `setup.py bdist_wheel -- -- -A Win32`) which works fine.

However, I am using [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) which (basically) uses `python -m build --wheel` under the hood, and I can use the `config-settings` to pass options to the underlying build tool.

```
CIBW_CONFIG_SETTINGS: --build-option="-- -- -A Win32"
```

Unfortunately, that doesn't work and I didn't find a way to get my `-A Win32` flag to be passed to the scikit-build options.

The furthest I can get with this is using:

```
CIBW_CONFIG_SETTINGS: --build-option="-- -A Win32"
```

Which sends the flag directly to the cmake, but then multiple `-A` flags end up in the cmake command and cmake complains and gives up.

So I then tried to use `SKBUILD_CONFIGURE_OPTIONS`, which also allows me to add the `-A` flag, but it also ends up double in the command.

So my suggestion is something like this:

```diff
diff --git a/skbuild/cmaker.py b/skbuild/cmaker.py
index 3d9835d..55584c2 100644
--- a/skbuild/cmaker.py
+++ b/skbuild/cmaker.py
@@ -273,8 +273,6 @@ class CMaker:
         cmd = [
             self.cmake_executable,
             cmake_source_dir,
-            "-G",
-            generator.name,
             f"-DCMAKE_INSTALL_PREFIX:PATH={cmake_install_prefix}",
             f"-DPYTHON_VERSION_STRING:STRING={python_version_string}",
             "-DSKBUILD:INTERNAL=TRUE",
@@ -301,15 +299,6 @@ class CMaker:

                 cmd.append(f"{prefix}_NumPy_INCLUDE_DIRS:PATH=" + np.get_include())

-        if generator.toolset:
-            cmd.extend(["-T", generator.toolset])
-        if generator.architecture:
-            cmd.extend(["-A", generator.architecture])
-        if ninja_executable_path is not None:
-            cmd.append(f"-DCMAKE_MAKE_PROGRAM:FILEPATH={ninja_executable_path}")
-
-        cmd.extend(clargs)
-
         # Parse CMAKE_ARGS only if SKBUILD_CONFIGURE_OPTIONS is not present
         if "SKBUILD_CONFIGURE_OPTIONS" in os.environ:
             env_cmake_args = list(filter(None, shlex.split(os.environ["SKBUILD_CONFIGURE_OPTIONS"])))
@@ -319,6 +308,17 @@ class CMaker:

         cmd.extend(env_cmake_args)

+        if not '-G' in cmd:
+            cmd.extend(["-G", generator.name])
+        if generator.toolset and not '-T' in cmd:
+            cmd.extend(["-T", generator.toolset])
+        if generator.architecture and not '-A' in cmd:
+            cmd.extend(["-A", generator.architecture])
+        if ninja_executable_path is not None:
+            cmd.append(f"-DCMAKE_MAKE_PROGRAM:FILEPATH={ninja_executable_path}")
+
+        cmd.extend(clargs)
+
         # changes dir to cmake_build and calls cmake's configure step
         # to generate makefile
         print(
```

It probably isn't the best way to do this though?
Would like to know your thoughts ;)

**Comment by henryiii** [comment]
In scikit-build-core we've switched to using `CMAKE_GENERATOR_PLATFORM` instead of `-A`, and it's only set if not already set. (also `CMAKE_GENERATOR` instead of `-G`, we don't actively set toolset anymore, but `CMAKE_GENERATOR_TOOLSET` is also available).

**Comment by vespakoen** [comment]
Hi Henry,

Thanks for taking a look at this.
I was not aware of scikit-build-core's existence, I think it will solve my problems and I will give it a try ;)

Thanks!
