### ISSUE TITLE
Shared library installs in wrong place when using nested package (package_dir)

### ISSUE THREAD

**Issue by jakobhu** [scikit-build/scikit-build#833]
I'm trying to add python bindings to an existing cmake based project.
I cannot share my project; however, I've managed to reproduce the problem using a modified version of the 'hello-cpp' example.
The problem I'm having is that the dynamic library ends up not being copied - or ends up in the wrong place when doing a pip install.

To reproduce (ubuntu 22.04):

```
unzip nested_test.zip
cd nested_test/
python -m venv env
source env/bin/activate
pip install -v . 

```
The installation seems to work, but looking more closely the package is not usable. the .so file ends up in the env/hello directory - not in the env/lib/python3.*/site-packages/hello directory ...

I've been trying the approach mentioned here: https://stackoverflow.com/questions/70044257/packaging-executable-shared-library-and-python-bindings-not-finding-library  - with no luck.

if I change the setup.py file from 
`
package_dir = {'': 'nested/hello-cpp'},`

to

`package_dir = {'hello': 'nested/hello-cpp'},`

then things look even worse. It seems that scikit-build doesn't like that the package directory is nested (via 'package_dir')

Any pointers to what I might be doing wrong or possible workarounds are much appreciated.

[nested_test.zip](https://github.com/scikit-build/scikit-build/files/10324596/nested_test.zip)

**Comment by tierriminator** [comment]
Your problem boils down to specifying the correct install location for your extension module.
What you basically want, is to install your extension module into a package, the same way as you put your `.py` module inside of a package. You can control this with a combination of two settings:

- The `DESTINATION` option of the CMake `install` command inside of your `CMakeLists.txt`
- The `cmake_install_dir` argument of `setup` in your `setup.py`, with which you can specify an installation prefix.

Those paths will be appended to give you the full path for where your target (the `.so` extension module) should be installed.
You are currently missing the `cmake_install_dir` option. So in your example above, just add
```
cmake_install_dir="nested/hello-cpp"
```

to your `setup` function in `setup.py` and your installation should succeed as expected.

**Comment by jakobhu** [comment]
Thank you.
