### ISSUE TITLE
Distutils removal (Python 3.12)

### ISSUE THREAD

**Issue by jakirkham** [scikit-build/scikit-build#841]
In Python 3.12, `distutils` is being removed ( [PEP 632]( https://peps.python.org/pep-0632/#backwards-compatibility ) ). In fact this has already happened in development ( https://github.com/python/cpython/issues/92584#issuecomment-1322708520 ). Not sure what (if any) are the implications for scikit-build, but wanted to raise this for awareness/discussion.

**Comment by henryiii** [comment]
Scikit-build-core already passes tests on 3.12. Might be interesting to just try it here too, though I'd rather hope we'll move to using scikit-build-core by the time 3.12 hits.

**Comment by jakirkham** [comment]
I see. Trying to wrap my head around how these relate.

Is scikit-build-core replacing scikit-build? Will scikit-build use scikit-build-core? Or is there some other relationship?

**Comment by henryiii** [comment]
Scikit-build-core provides two things - a PEP 517 builder, and tooling to make extension building plugins. The former "replaces" scikit-build, and is the preferred path forward. The later is being used to build a setuptools plugin, which will become what scikit-build uses (to support existing projects with a forward migration plan and getting some of the benefits without having to change code).

**Comment by henryiii** [comment]
FYI, both scikit-build-core and scikit-build are running on Python 3.12 alphas. So even if we don't swap out the backend before release (which we are still on track to do), it should be fine. The `distutils` module gets injected by `setuptools`, so the initial goal is to make sure "local" distutils is supported.
