### ISSUE TITLE
Maybe treat AttributeError like ModuleNotFoundError for cmake discovery

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [scikit-build/scikit-build#845]
Here is the trace:

```
File "/home/runner/work/dpctl/dpctl/setup.py", line 23, in <module>
    import skbuild
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/skbuild/__init__.py", line 10, in <module>
    from .setuptools_wrap import setup
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line [39](https://github.com/IntelPython/dpctl/actions/runs/3962549168/jobs/6789348648#step:9:40), in <module>
    from . import cmaker
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/skbuild/cmaker.py", line 25, in <module>
    from .constants import (
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/skbuild/constants.py", line 33, in <module>
    CMAKE_DEFAULT_EXECUTABLE = _get_cmake_executable()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/skbuild/constants.py", line 19, in _get_cmake_executable
    path = f"{cmake.CMAKE_BIN_DIR}/cmake"
AttributeError: module 'cmake' has no attribute 'CMAKE_BIN_DIR'
```

A work-around is to use scikit-build 0.16.4

**Comment by oleksandr-pavlyk** [comment]
What has happened, is that I had `cmake` conda package installed in the environment, so `import cmake` went through, but the package did not provide `CMAKE_BIN_DIR` attribute, so the `AttributeError` was raised.

Running `pip install cmake` to install 3.25 did solve the issue for me.

It would be nice to perhaps also suppress the `AttributeError`, in addition to suppressing the `ModuleNotFoundError`, or perhaps check for the attribute before accessing it.

**Comment by henryiii** [comment]
```console
$ mamba create -n cmakecheck -c conda-forge cmake python==3.11
$ conda activate cmakecheck
$ python -c "import cmake"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'cmake'
```

**Comment by trxcllnt** [comment]
I'm also seeing this error. In my case, this happens when we do an editable install of a project that contains a `cmake` directory of CMake helpers/modules etc.

This example is representative of what I'm seeing:

```shell
# assume python package is named "foo_py"
$ ls ~/repo
~/repo/foo_py # <-- python source code
~/repo/cmake/Modules # <-- cmake modules
~/repo/CMakeLists.txt
~/repo/setup.py
~/repo/pyproject.toml
...

# install foo_py in editable mode. the .egg-link points to ~/repo
$ pip install -e repo

# `import cmake` imports ~/repo/cmake
$ python -c 'import cmake; print(list(cmake.__path__))'
['/home/repo/cmake']
```

**Comment by henryiii** [comment]
Yes, that would do it.

**Comment by henryiii** [comment]
I've yanked 0.16.5, so pinning or capping (or excluding, which is better) shouldn't be required. I'll get 0.16.6 out soon.

**Comment by marcinz** [comment]
Is there a way to yank it from conda too? The package seems to still be there.

**Comment by henryiii** [comment]
Yes, but there I have to mark it as broken. https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages

By the time that goes through, I'll likely have a patch release out.

**Comment by henryiii** [comment]
I'll push a release as soon as #848 and $850 go in.

**Comment by henryiii** [comment]
Released, https://github.com/conda-forge/scikit-build-feedstock/pull/67 for conda-forge.
