### ISSUE TITLE
Possible to override pyproject.toml project version?

### ISSUE THREAD

**Issue by alugowski** [scikit-build/scikit-build#846]
I'm building Python bindings for a C++ library. The C++ library defines its version and I'd like the Python bindings to have the same version.

Currently have this in my pyproject.toml:
```toml
[project]
version = "1.4.0"
```

Is it possible to override this value on the command-line somehow so my CI can set the value to match the C++ library's?

**Comment by henryiii** [comment]
It is invalid to use `[project]` partially. You must use a build backend (like scikit-build-core) that supports `[project]`. And you must define at least the name and version (though version can be dynamic).

Eventually, scikit-build-core will support setuptools-scm, which supports setting this via a config variable. It should also support setting it in CMake.

If you are not using the `[project]` table, then you can mix scikit-build and setuptools_scm, which allows this.

**Comment by alugowski** [comment]
Of course I have the entire `[project]` filled out, but only included the lines I thought were relevant to the question. Complete file [here](https://github.com/alugowski/fast_matrix_market/blob/main/python/pyproject.toml)

I do use `scikit_build_core`, it just now clicked that these are two different projects! Appologies for posting in the wrong place. I'm using only `pyproject.toml`, so it sounds like this will be possible in the future but not right now?

By the way thank you for building this. Scikit-build-core, pybind11, and cibuildwheel together make building a Python extension a downright joy compared to what it took last time I was down this path 8 years ago.

**Comment by henryiii** [comment]
Ah, makes much more sense. Yep, it will be possible in the not too distant future. I've got some preparatory work in a branch for it, in fact. Just have to work out the design, making it general enough but not too general.
