### ISSUE TITLE
Fix python setup.py build bdist_wheel

### ISSUE THREAD

**Issue by thewtex** [scikit-build/scikit-build#85]
Currently outputs::

  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

  error: invalid command 'bdist_wheel'

**Comment by opadron** [comment]
#89

**Comment by jcfr** [comment]
Cc: @opadron @msmolens @thewtex  

To keep clarify in the history of the code, I am reorganizing the commits that were integrated as of https://github.com/scikit-build/scikit-build/pull/89 and will push force. Noise (addition of change, partial revert, ... ) was introduced in critical part of the code by the sequences of commits. This makes it hard to review and track the changes.

When done, you will have to `rebase --onto` of your currently open topics.
