### ISSUE TITLE
RFC: Transition to py.test

### ISSUE THREAD

**Issue by jcfr** [scikit-build/scikit-build#91]
The `py.test` framework integrates better with setuptools.

See http://docs.pytest.org/en/latest/goodpractices.html#integrating-with-setuptools-python-setup-py-test-pytest-runner

It will also allow to remove workaround discussed in #90

**Comment by thewtex** [comment]
+1 The original nose is not being maintained, and many projects are moving to py.test.

From https://nose.readthedocs.io/en/latest/:

> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2.
