### ISSUE TITLE
cross compiling for Windows Arm64

### ISSUE THREAD

**Issue by maxbachmann** [scikit-build/scikit-build#912]
From the release notes there is experimental support to cross compile for Windows Arm64 using cibuildwheel since version [0.16.4](https://github.com/scikit-build/scikit-build/releases/tag/0.16.4). I did try to use this in my projects which fails with linker errors about missing symbols: https://github.com/maxbachmann/RapidFuzz/actions/runs/4615046555/jobs/8158606227. Disabling LTO leads to a different set of linker errors: https://github.com/maxbachmann/RapidFuzz/actions/runs/4630266637/jobs/8191700581. Is there anything in particular that need to be changed in projects for this to work?

**Comment by henryiii** [comment]
It's linking to the wrong library. Currently, we don't have the python library artifact specified, but it [seems to be supported](https://cmake.org/cmake/help/latest/module/FindPython.html#artifacts-specification) (maybe starting in 3.16?), so let's try that.
